import { StyleDefinition } from '../../core/types/style-definition';

export const cyberpunkStyle: StyleDefinition = {
  id: 'cyberpunk',
  name: 'Cyberpunk',
  description: 'High-tech low-life terminal aesthetic featuring chamfered polygon corners, luminescent neon cyan and hot laser magenta glows, scanlines, HUD telemetry overlays, and monospaced console tags.',
  metadata: {
    version: '1.0.0',
    category: 'Expressive',
    tags: ['cyberpunk', 'neon', 'sci-fi', 'hud', 'terminal', 'glow', 'futuristic'],
  },
  compositionConfig: {
    containerPhilosophy: 'hud-frame',
    groupingPhilosophy: 'telemetry-nodes',
    featurePresentation: 'hud-node',
    heroMode: 'hud-matrix',
    maxWidth: '1280px',
    alignment: 'technical-grid',
    density: 'compact',
    hasStructuralBorders: true,
    hasAsymmetricOffsets: false,
    hasDecorativeFraming: true,
  },
  tokens: {
    colors: {
      background: '#07090e', // Deep obsidian void
      surface: '#0e111a',
      surfaceSubtle: '#161b26',
      textPrimary: '#00f0ff', // Electric neon cyan
      textSecondary: '#e2e8f0',
      textMuted: '#64748b',
      primary: '#ffe600', // Acid yellow cyber laser
      primaryHover: '#00f0ff',
      primaryText: '#000000',
      accent: '#ff0055', // Hot laser magenta
      border: '#00f0ff',
      borderStrong: '#ff0055',
      ring: 'rgba(0, 240, 255, 0.4)',
    },
    typography: {
      fontFamilyBase: "'JetBrains Mono', 'Fira Code', monospace",
      fontFamilyHeading: "'JetBrains Mono', 'Space Grotesk', monospace",
      fontFamilyMono: "'JetBrains Mono', monospace",
      fontSizeXs: '0.75rem',
      fontSizeSm: '0.875rem',
      fontSizeBase: '1rem',
      fontSizeLg: '1.25rem',
      fontSizeXl: '1.75rem',
      fontSize2xl: '2.5rem',
      fontWeightNormal: 400,
      fontWeightMedium: 700,
      fontWeightBold: 900,
      lineHeightBase: 1.5,
      lineHeightHeading: 1.1,
      letterSpacingBase: '0.02em',
      letterSpacingHeading: '0.06em',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1rem',
      lg: '2rem',
      xl: '3rem',
      '2xl': '4.5rem',
    },
    radii: {
      none: '0px',
      sm: '0px',
      md: '0px',
      lg: '0px',
      full: '0px',
    },
    borders: {
      widthThin: '1px',
      widthBase: '2px',
      widthThick: '3px',
      style: 'solid',
    },
    shadows: {
      none: 'none',
      sm: '0 0 10px rgba(0, 240, 255, 0.3)',
      md: '0 0 20px rgba(0, 240, 255, 0.45)',
      lg: '0 0 35px rgba(255, 0, 85, 0.4)',
      glow: '0 0 25px rgba(0, 240, 255, 0.6)',
    },
    motion: {
      durationFast: '80ms',
      durationNormal: '150ms',
      easing: 'cubic-bezier(0, 0, 0.2, 1)',
    },
    effects: {
      backdropBlur: 'none',
      transformHover: 'translate(-2px, -2px)',
    },
  },
  components: {
    button: {
      padding: '0.75rem 1.75rem',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '0.875rem',
      fontWeight: 800,
      letterSpacing: '0.08em',
      textTransform: 'uppercase',
      borderRadius: '0px',
      borderWidth: '2px',
      borderStyle: 'solid',
      borderColor: '#00f0ff',
      background: '#ffe600',
      color: '#000000',
      boxShadow: '0 0 15px rgba(255, 230, 0, 0.5)',
      transition: 'all 120ms ease',
      hover: {
        background: '#00f0ff',
        color: '#000000',
        borderColor: '#ff0055',
        boxShadow: '0 0 25px rgba(0, 240, 255, 0.8)',
      },
      active: {
        background: '#ff0055',
        color: '#ffffff',
      },
      focusRing: '0 0 0 3px rgba(0, 240, 255, 0.5)',
    },
    card: {
      padding: '2rem',
      borderRadius: '0px',
      borderWidth: '2px',
      borderStyle: 'solid',
      borderColor: '#00f0ff',
      background: '#0e111a',
      color: '#e2e8f0',
      boxShadow: '0 0 20px rgba(0, 240, 255, 0.25)',
      transition: 'border-color 150ms ease, box-shadow 150ms ease',
      hover: {
        borderColor: '#ff0055',
        boxShadow: '0 0 30px rgba(255, 0, 85, 0.4)',
      },
    },
    heading: {
      fontFamily: "'JetBrains Mono', 'Space Grotesk', monospace",
      fontWeight: 900,
      letterSpacing: '0.06em',
      lineHeight: 1.1,
      color: '#00f0ff',
      textTransform: 'uppercase',
    },
    paragraph: {
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '0.9375rem',
      lineHeight: 1.5,
      color: '#e2e8f0',
    },
    input: {
      padding: '0.75rem 1rem',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '0.875rem',
      borderRadius: '0px',
      borderWidth: '2px',
      borderStyle: 'solid',
      borderColor: '#00f0ff',
      background: '#07090e',
      color: '#00f0ff',
      placeholderColor: '#64748b',
      boxShadow: 'none',
      focusBorderColor: '#ff0055',
      focusRing: '0 0 0 3px rgba(255, 0, 85, 0.4)',
      transition: 'border-color 120ms ease, box-shadow 120ms ease',
    },
    badge: {
      padding: '0.25rem 0.6rem',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '0.75rem',
      fontWeight: 800,
      letterSpacing: '0.1em',
      textTransform: 'uppercase',
      borderRadius: '0px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#00f0ff',
      background: '#ff0055',
      color: '#ffffff',
    },
    section: {
      padding: '3.5rem 2rem',
      background: '#0e111a',
      borderColor: '#00f0ff',
      borderWidth: '1px',
      borderStyle: 'solid',
    },
    page: {
      background: '#07090e',
      color: '#00f0ff',
      fontFamily: "'JetBrains Mono', monospace",
    },
  },
};

export { cyberpunkSemanticCss } from './rules';
