import { StyleDefinition } from '../../core/types/style-definition';

export const neoBrutalismStyle: StyleDefinition = {
  id: 'neo-brutalism',
  name: 'Neo-Brutalism',
  description: 'Bold structural outlines, tactile hard-offset shadows, friendly rounded geometry, punchy saturated pop accents, and high-contrast contemporary grotesk typography.',
  metadata: {
    version: '1.0.0',
    category: 'Expressive',
    tags: ['neo-brutalism', 'bold', 'tactile', 'playful', 'geometric', 'pop', 'offset-shadow'],
  },
  tokens: {
    colors: {
      background: '#fffdfa', // Warm optimistic paper tone
      surface: '#ffffff',
      surfaceSubtle: '#fff8eb',
      textPrimary: '#121212', // Punchy deep ink
      textSecondary: '#374151',
      textMuted: '#6b7280',
      primary: '#ff5a5f', // Vibrant electric coral
      primaryHover: '#ff4338',
      primaryText: '#ffffff',
      accent: '#ffde59', // Sunny yellow
      border: '#121212',
      borderStrong: '#121212',
      ring: 'rgba(255, 90, 95, 0.4)',
    },
    typography: {
      fontFamilyBase: "'Plus Jakarta Sans', 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      fontFamilyHeading: "'Plus Jakarta Sans', 'Space Grotesk', sans-serif",
      fontFamilyMono: "'JetBrains Mono', monospace",
      fontSizeXs: '0.75rem',
      fontSizeSm: '0.875rem',
      fontSizeBase: '1rem',
      fontSizeLg: '1.25rem',
      fontSizeXl: '1.75rem',
      fontSize2xl: '2.75rem',
      fontWeightNormal: 500,
      fontWeightMedium: 700,
      fontWeightBold: 800,
      lineHeightBase: 1.6,
      lineHeightHeading: 1.06,
      letterSpacingBase: '0em',
      letterSpacingHeading: '-0.03em',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1.25rem',
      lg: '2.25rem',
      xl: '3.5rem',
      '2xl': '5rem',
    },
    radii: {
      none: '0px',
      sm: '8px',
      md: '12px',
      lg: '16px',
      full: '9999px',
    },
    borders: {
      widthThin: '1.5px',
      widthBase: '2px',
      widthThick: '3px',
      style: 'solid',
    },
    shadows: {
      none: 'none',
      sm: '3px 3px 0px #121212',
      md: '4px 4px 0px #121212',
      lg: '6px 6px 0px #121212',
      glow: '0px 0px 0px 3px #121212',
    },
    motion: {
      durationFast: '100ms',
      durationNormal: '160ms',
      easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    },
    effects: {
      backdropBlur: 'none',
      transformHover: 'translate(2px, 2px)',
    },
  },
  components: {
    button: {
      padding: '0.85rem 1.75rem',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '0.9375rem',
      fontWeight: 800,
      letterSpacing: '0.02em',
      textTransform: 'none',
      borderRadius: '10px',
      borderWidth: '2px',
      borderStyle: 'solid',
      borderColor: '#121212',
      background: '#ff5a5f',
      color: '#ffffff',
      boxShadow: '4px 4px 0px #121212',
      transition: 'transform 100ms ease, box-shadow 100ms ease, background-color 100ms ease',
      hover: {
        background: '#ff4338',
        borderColor: '#121212',
        color: '#ffffff',
      },
      active: {
        background: '#e0363b',
        borderColor: '#121212',
      },
      focusRing: '0 0 0 3px rgba(255, 90, 95, 0.4)',
    },
    card: {
      padding: '2.25rem 2rem',
      borderRadius: '12px',
      borderWidth: '2px',
      borderStyle: 'solid',
      borderColor: '#121212',
      background: '#ffffff',
      color: '#121212',
      boxShadow: '4px 4px 0px #121212',
      transition: 'transform 120ms ease, box-shadow 120ms ease',
      hover: {
        borderColor: '#121212',
      },
    },
    heading: {
      fontFamily: "'Plus Jakarta Sans', 'Space Grotesk', sans-serif",
      fontWeight: 900,
      letterSpacing: '-0.03em',
      lineHeight: 1.06,
      color: '#121212',
    },
    paragraph: {
      fontFamily: "'Plus Jakarta Sans', 'Inter', sans-serif",
      fontSize: '1.0625rem',
      lineHeight: 1.65,
      color: '#374151',
    },
    input: {
      padding: '0.85rem 1.15rem',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '0.9375rem',
      borderRadius: '8px',
      borderWidth: '2px',
      borderStyle: 'solid',
      borderColor: '#121212',
      background: '#ffffff',
      color: '#121212',
      placeholderColor: '#6b7280',
      focusBorderColor: '#121212',
      focusRing: '0 0 0 3px #ff5a5f',
      transition: 'all 120ms ease',
    },
    badge: {
      padding: '0.3rem 0.85rem',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '0.75rem',
      fontWeight: 800,
      letterSpacing: '0.08em',
      textTransform: 'uppercase',
      borderRadius: '9999px',
      borderWidth: '2px',
      borderStyle: 'solid',
      borderColor: '#121212',
      background: '#ffde59',
      color: '#121212',
      boxShadow: '2.5px 2.5px 0px #121212',
    },
    section: {
      padding: '3.5rem 2rem',
      background: 'transparent',
      borderColor: '#121212',
      borderWidth: '2px',
      borderStyle: 'none',
    },
    page: {
      background: '#fffdfa',
      color: '#121212',
      fontFamily: "'Plus Jakarta Sans', 'Inter', sans-serif",
    },
  },
};

export { neoBrutalistSemanticCss } from './rules';
