import { StyleDefinition } from '../../core/types/style-definition';

export const surrealismStyle: StyleDefinition = {
  id: 'surrealism',
  name: 'Surrealism',
  description: 'Dreamlike logic, sculptural editorial serifs, atmospheric twilight haze, celestial orbit motifs, asymmetric portal curvature, and uncanny scale tension.',
  metadata: {
    version: '1.0.0',
    category: 'Artistic & Organic',
    tags: ['surrealism', 'dreamlike', 'sculptural', 'editorial-serif', 'celestial', 'poetic', 'asymmetry'],
  },
  tokens: {
    colors: {
      background: '#f5f2eb', // Warm alabaster dreamscape canvas
      surface: '#ffffff',
      surfaceSubtle: '#ece7df',
      textPrimary: '#16151a', // Deep surreal ink
      textSecondary: '#4a4552',
      textMuted: '#7e7888',
      primary: '#3b1124', // Deep dream burgundy
      primaryHover: '#d97762', // Surreal terracotta
      primaryText: '#ffffff',
      accent: '#d97762',
      border: '#d1c9bd',
      borderStrong: '#3b1124',
      ring: 'rgba(217, 119, 98, 0.35)',
    },
    typography: {
      fontFamilyBase: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      fontFamilyHeading: "'Playfair Display', 'Cormorant Garamond', 'Georgia', serif",
      fontFamilyMono: "'JetBrains Mono', monospace",
      fontSizeXs: '0.6875rem',
      fontSizeSm: '0.8125rem',
      fontSizeBase: '1rem',
      fontSizeLg: '1.35rem',
      fontSizeXl: '2rem',
      fontSize2xl: '3rem',
      fontWeightNormal: 400,
      fontWeightMedium: 600,
      fontWeightBold: 700,
      lineHeightBase: 1.65,
      lineHeightHeading: 1.08,
      letterSpacingBase: '0em',
      letterSpacingHeading: '-0.025em',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1.25rem',
      lg: '2.5rem',
      xl: '4rem',
      '2xl': '6rem',
    },
    radii: {
      none: '0px',
      sm: '8px',
      md: '24px 8px 24px 8px', // Asymmetric portal curvature
      lg: '36px 8px 36px 8px',
      full: '9999px',
    },
    borders: {
      widthThin: '1px',
      widthBase: '1px',
      widthThick: '2px',
      style: 'solid',
    },
    shadows: {
      none: 'none',
      sm: '0 4px 14px rgba(59, 17, 36, 0.12)',
      md: '0 8px 24px -4px rgba(59, 17, 36, 0.16)',
      lg: '0 16px 36px -6px rgba(59, 17, 36, 0.25)',
      glow: '0 0 20px rgba(217, 119, 98, 0.4)',
    },
    motion: {
      durationFast: '160ms',
      durationNormal: '240ms',
      easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    },
    effects: {
      backdropBlur: 'none',
      transformHover: 'translateY(-2px)',
    },
  },
  components: {
    button: {
      padding: '0.85rem 2rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.875rem',
      fontWeight: 600,
      letterSpacing: '0.06em',
      textTransform: 'none',
      borderRadius: '9999px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#2d121e',
      background: '#2d121e',
      color: '#ffffff',
      boxShadow: '0 4px 16px rgba(45, 18, 30, 0.24)',
      transition: 'all 220ms cubic-bezier(0.16, 1, 0.3, 1)',
      hover: {
        background: '#d97762',
        borderColor: '#d97762',
        color: '#ffffff',
      },
      active: {
        background: '#1c0a13',
        borderColor: '#1c0a13',
      },
      focusRing: '0 0 0 3px rgba(217, 119, 98, 0.35)',
    },
    card: {
      padding: '2.5rem 2rem',
      borderRadius: '28px 8px 28px 8px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: 'rgba(209, 201, 189, 0.75)',
      background: 'rgba(255, 255, 255, 0.75)',
      color: '#151419',
      boxShadow: '0 8px 24px -4px rgba(45, 18, 30, 0.06)',
      transition: 'transform 220ms ease, box-shadow 220ms ease',
      hover: {
        borderColor: '#d97762',
      },
    },
    heading: {
      fontFamily: "'Playfair Display', 'Cormorant Garamond', 'Georgia', serif",
      fontWeight: 700,
      letterSpacing: '-0.025em',
      lineHeight: 1.08,
      color: '#151419',
    },
    paragraph: {
      fontFamily: "'Inter', -apple-system, sans-serif",
      fontSize: '1.03125rem',
      lineHeight: 1.72,
      color: '#3b3742',
    },
    input: {
      padding: '0.85rem 1.15rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.9375rem',
      borderRadius: '14px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#d1c9bd',
      background: '#ffffff',
      color: '#151419',
      placeholderColor: '#7e7888',
      focusBorderColor: '#d97762',
      focusRing: '0 0 0 3px rgba(217, 119, 98, 0.22)',
      transition: 'border-color 180ms ease, box-shadow 180ms ease',
    },
    badge: {
      padding: '0.35rem 0.85rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.6875rem',
      fontWeight: 700,
      letterSpacing: '0.22em',
      textTransform: 'uppercase',
      borderRadius: '9999px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: 'rgba(217, 119, 98, 0.3)',
      background: 'rgba(217, 119, 98, 0.1)',
      color: '#d97762',
    },
    section: {
      padding: '4rem 2rem',
      background: 'transparent',
      borderColor: 'rgba(209, 201, 189, 0.7)',
      borderWidth: '1px',
      borderStyle: 'none',
    },
    page: {
      background: '#f7f4ed',
      color: '#151419',
      fontFamily: "'Inter', -apple-system, sans-serif",
    },
  },
};

export { surrealDesignSemanticCss } from './rules';
