import { StyleDefinition } from '../../core/types/style-definition';

export const editorialDesignStyle: StyleDefinition = {
  id: 'editorial-design',
  name: 'Editorial Design',
  description: 'Broadsheet publishing layout, authoritative serif headlines, journalistic decks, byline metadata, and narrative reading rhythm.',
  metadata: {
    version: '1.0.0',
    category: 'Modern',
    tags: ['editorial-design', 'publishing', 'magazine', 'broadsheet', 'journalism', 'typography', 'narrative'],
  },
  tokens: {
    colors: {
      background: '#fbfaf7', // Warm newsprint paper
      surface: '#ffffff',
      surfaceSubtle: '#f7f5ef',
      textPrimary: '#141413', // Deep publication black
      textSecondary: '#4b5563', // Broadsheet charcoal
      textMuted: '#71717a',
      primary: '#141413',
      primaryHover: '#991b1b',
      primaryText: '#fbfaf7',
      accent: '#991b1b', // Deep editorial crimson
      border: '#e5e0d8', // Broadsheet hairline
      borderStrong: '#141413',
      ring: 'rgba(153, 27, 27, 0.35)',
    },
    typography: {
      fontFamilyBase: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      fontFamilyHeading: "'Newsreader', 'Playfair Display', 'Cormorant Garamond', 'Georgia', serif",
      fontFamilyMono: "'JetBrains Mono', monospace",
      fontSizeXs: '0.6875rem',
      fontSizeSm: '0.8125rem',
      fontSizeBase: '1.03125rem',
      fontSizeLg: '1.35rem',
      fontSizeXl: '2rem',
      fontSize2xl: '3rem',
      fontWeightNormal: 400,
      fontWeightMedium: 600,
      fontWeightBold: 700,
      lineHeightBase: 1.78,
      lineHeightHeading: 1.08,
      letterSpacingBase: '0.005em',
      letterSpacingHeading: '-0.025em',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1.25rem',
      lg: '2.5rem',
      xl: '4rem',
      '2xl': '6rem',
    },
    radii: {
      none: '0px',
      sm: '2px',
      md: '2px',
      lg: '4px',
      full: '9999px',
    },
    borders: {
      widthThin: '1px',
      widthBase: '1px',
      widthThick: '2px',
      style: 'solid',
    },
    shadows: {
      none: 'none',
      sm: '0 1px 3px rgba(0, 0, 0, 0.04)',
      md: '0 2px 6px rgba(0, 0, 0, 0.06)',
      lg: '0 6px 16px rgba(0, 0, 0, 0.08)',
      glow: 'none',
    },
    motion: {
      durationFast: '140ms',
      durationNormal: '220ms',
      easing: 'ease',
    },
    effects: {
      backdropBlur: 'none',
      transformHover: 'none',
    },
  },
  components: {
    button: {
      padding: '0.85rem 2.25rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.75rem',
      fontWeight: 700,
      letterSpacing: '0.14em',
      textTransform: 'uppercase',
      borderRadius: '2px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#141413',
      background: '#141413',
      color: '#fbfaf7',
      boxShadow: 'none',
      transition: 'all 160ms ease',
      hover: {
        background: '#991b1b',
        borderColor: '#991b1b',
        color: '#ffffff',
      },
      active: {
        background: '#7f1d1d',
        borderColor: '#7f1d1d',
      },
      focusRing: '0 0 0 2px rgba(153, 27, 27, 0.4)',
    },
    card: {
      padding: '3rem 2rem',
      borderRadius: '2px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#e5e0d8',
      background: '#ffffff',
      color: '#141413',
      boxShadow: 'none',
      transition: 'border-color 180ms ease',
      hover: {
        borderColor: '#141413',
      },
    },
    heading: {
      fontFamily: "'Newsreader', 'Playfair Display', 'Cormorant Garamond', 'Georgia', serif",
      fontWeight: 700,
      letterSpacing: '-0.025em',
      lineHeight: 1.08,
      color: '#141413',
    },
    paragraph: {
      fontFamily: "'Inter', -apple-system, sans-serif",
      fontSize: '1.03125rem',
      lineHeight: 1.78,
      color: '#262626',
    },
    input: {
      padding: '0.85rem 1.15rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.9375rem',
      borderRadius: '2px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#d4cebe',
      background: '#ffffff',
      color: '#141413',
      placeholderColor: '#71717a',
      focusBorderColor: '#991b1b',
      focusRing: 'none',
      transition: 'border-color 160ms ease',
    },
    badge: {
      padding: '0.35rem 0.75rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.6875rem',
      fontWeight: 800,
      letterSpacing: '0.2em',
      textTransform: 'uppercase',
      borderRadius: '2px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#991b1b',
      background: '#fbfaf7',
      color: '#991b1b',
    },
    section: {
      padding: '4.5rem 2rem',
      background: 'transparent',
      borderColor: '#e5e0d8',
      borderWidth: '1px',
      borderStyle: 'none',
    },
    page: {
      background: '#fbfaf7',
      color: '#141413',
      fontFamily: "'Inter', -apple-system, sans-serif",
    },
  },
};

export { editorialDesignSemanticCss } from './rules';
