export interface StyleCatalogItem {
  id: string;
  name: string;
  category: 'Modern' | 'Expressive' | 'Material & Depth' | 'Retro & Heritage' | 'Artistic & Organic';
  status: 'active' | 'upcoming';
  tagline: string;
  description: string;
  accentColor: string;
  previewGradient: string;
  features: string[];
}

export const ALL_29_STYLES: StyleCatalogItem[] = [
  {
    id: 'minimalism',
    name: 'Minimalism',
    category: 'Modern',
    status: 'active',
    tagline: 'Less is more. Intentional space and quiet hierarchy.',
    description: 'Restrained typography, subtle hairline borders, spacious margins, and calm monochromatic harmony.',
    accentColor: '#18181b',
    previewGradient: 'linear-gradient(135deg, #f4f4f5 0%, #e4e4e7 100%)',
    features: ['Hairline 1px borders', 'Generous whitespace', 'Monochromatic tones', '500 weight typography'],
  },
  {
    id: 'brutalism',
    name: 'Brutalism',
    category: 'Expressive',
    status: 'active',
    tagline: 'Raw, tactile, unpolished visual impact.',
    description: 'Thick 3px solid black borders, 0px sharp corners, hard offset drop shadows, uppercase tracking, and neon acid accents.',
    accentColor: '#ffe600',
    previewGradient: 'linear-gradient(135deg, #ffe600 0%, #ff3366 100%)',
    features: ['Thick 3px solid borders', '0px sharp corners', 'Hard 4px offset shadows', 'Uppercase bold text'],
  },
  {
    id: 'glassmorphism',
    name: 'Glassmorphism',
    category: 'Material & Depth',
    status: 'active',
    tagline: 'Frosted translucency, optical blur, and layered luminescence.',
    description: 'Frosted glass surfaces with 20px blur, delicate light-catching borders, glowing aura shadows, and rounded glass pills.',
    accentColor: '#38bdf8',
    previewGradient: 'linear-gradient(135deg, rgba(99, 102, 241, 0.4) 0%, rgba(56, 189, 248, 0.3) 100%)',
    features: ['20px backdrop blur', 'Translucent glass borders', 'Glowing ambient shadows', 'Pill radii (9999px)'],
  },
  {
    id: 'maximalism',
    name: 'Maximalism',
    category: 'Expressive',
    status: 'active',
    tagline: 'Rich, layered, expressive visual density.',
    description: 'Layered tactile parchment, royal crimson and saffron accents, expressive display serif typography, and controlled visual density.',
    accentColor: '#701a2b',
    previewGradient: 'linear-gradient(135deg, #701a2b 0%, #1e40af 50%, #d97706 100%)',
    features: ['Tactile parchment foundation', 'Expressive display serifs', 'Deterministic collection variation', 'Firm offset tactile shadows'],
  },
  {
    id: 'swiss-design',
    name: 'Swiss Design',
    category: 'Modern',
    status: 'active',
    tagline: 'Mathematical grids, objective clarity, and asymmetric precision.',
    description: 'Objective sans-serif typography, disciplined horizontal datum lines, asymmetric whitespace, flat planar geometry, and restrained Swiss Red (#dc2626) information signals.',
    accentColor: '#ef4444',
    previewGradient: 'linear-gradient(135deg, #000000 0%, #ef4444 50%, #ffffff 100%)',
    features: ['Objective typography', 'Horizontal datum lines', '0px planar geometry', 'Restrained Swiss Red signal'],
  },
  {
    id: 'surrealism',
    name: 'Surrealism',
    category: 'Artistic & Organic',
    status: 'active',
    tagline: 'Dreamlike logic, poetic contradiction, uncanny depth, and celestial harmony.',
    description: 'Sculptural editorial serifs, ethereal twilight atmosphere, celestial orbit lines, asymmetric portal curves, and unexpected scale tension.',
    accentColor: '#d97762',
    previewGradient: 'linear-gradient(135deg, #3b1124 0%, #d97762 50%, #f5f2eb 100%)',
    features: ['Sculptural serif hierarchy', 'Warm alabaster canvas', 'Celestial orbit lines', 'Asymmetric portal curvature'],
  },
  {
    id: 'neo-brutalism',
    name: 'Neo-Brutalism',
    category: 'Expressive',
    status: 'active',
    tagline: 'High-contrast outlines, tactile offset shadows, friendly geometry, and saturated pop energy.',
    description: 'Bold grotesk typography, 2px structural dark outlines, tactile hard-offset shadows, warm paper foundation, and punchy electric coral and sunny yellow accents.',
    accentColor: '#ff5a5f',
    previewGradient: 'linear-gradient(135deg, #121212 0%, #ff5a5f 50%, #ffde59 100%)',
    features: ['2px structural outlines', 'Tactile hard-offset shadows', 'Friendly rounded geometry', 'Saturated pop accent blocks'],
  },
  {
    id: 'neo-classical',
    name: 'Neo-Classical',
    category: 'Retro & Heritage',
    status: 'active',
    tagline: 'Classical architectural proportion, typographic refinement, and modern digital usability.',
    description: 'Proportion, symmetry, refined display serifs paired with functional sans, structural hairlines and double rules, and warm ivory paper foundation.',
    accentColor: '#b89758',
    previewGradient: 'linear-gradient(135deg, #1a1917 0%, #b89758 50%, #fcfbf7 100%)',
    features: ['Classical proportion & symmetry', 'Display serif & functional sans', 'Structural double rules & hairlines', 'Warm ivory parchment paper'],
  },
  {
    id: 'neumorphism',
    name: 'Neumorphism',
    category: 'Material & Depth',
    status: 'active',
    tagline: 'Soft extruded surfaces, tactile depth, and continuous physical controls.',
    description: 'Low-contrast continuous surfaces with dual-direction soft shadows simulating physical objects molded from one continuous material.',
    accentColor: '#3b82f6',
    previewGradient: 'linear-gradient(135deg, #e0e5ec 0%, #cbd5e1 50%, #ffffff 100%)',
    features: ['Dual-direction soft shadows', 'Seamless material fusion', 'Physically recessed inputs', 'Tactile extruded controls'],
  },
  {
    id: 'scrapbook',
    name: 'Scrapbook',
    category: 'Artistic & Organic',
    status: 'active',
    tagline: 'Physical memory book aesthetic, washi tape cues, handwritten annotations, and collected paper ephemera.',
    description: 'Layered paper textures (#f7f3e8 album paper, #fffef9 photo cards, #fef08a sticky notes), washi tape cues, slight organic rotations, Playfair Display & Lora typography with Caveat handwriting, and stamped tags.',
    accentColor: '#b91c1c',
    previewGradient: 'linear-gradient(135deg, #f7f3e8 0%, #fffef9 50%, #fef08a 100%)',
    features: ['Layered paper sheets & cards', 'Washi tape & ticket cues', 'Handwritten Caveat notes', 'Stamped vintage labels'],
  },
  {
    id: 'claymorphism',
    name: 'Claymorphism',
    category: 'Material & Depth',
    status: 'active',
    tagline: 'Soft molded clay surfaces, inflated 3D forms, and friendly tactile controls.',
    description: 'Soft inflated white and pastel clay slabs with dual inner diffuse highlights, pillowy rounded geometry, ambient floating drop shadows, and friendly tactile controls.',
    accentColor: '#6366f1',
    previewGradient: 'linear-gradient(135deg, #f6f3eb 0%, #ede9fe 50%, #dbeafe 100%)',
    features: ['Inflated 3D clay volumes', 'Dual inset diffuse highlights', 'Generous 30px pillowy radii', 'Tactile squish physical states'],
  },
  {
    id: 'bento-grid',
    name: 'Bento Grid',
    category: 'Modern',
    status: 'active',
    tagline: 'Modular, compartmentalized content packaging with high density.',
    description: 'Asymmetrical yet harmonious grid tiles inspired by Japanese bento boxes, grouping diverse cards effortlessly.',
    accentColor: '#6366f1',
    previewGradient: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 100%)',
    features: ['Varied tile spans', 'Consistent corner radii', 'High information density', 'Sleek dark mode base'],
  },
  {
    id: 'pixel-art',
    name: 'Pixel Art',
    category: 'Retro & Heritage',
    status: 'active',
    tagline: '8-bit arcade nostalgia, aliased outlines, and retro CRT vibes.',
    description: 'Aliased stepped borders, bitmap typography, limited 16-color palettes, and retro gaming telemetry.',
    accentColor: '#22c55e',
    previewGradient: 'linear-gradient(135deg, #052e16 0%, #14532d 100%)',
    features: ['Chunky pixel grids', 'Aliased hard borders', 'Pixelated monospace type', 'CRT scanline effects'],
  },
  {
    id: 'conceptual-sketch',
    name: 'Conceptual Sketch',
    category: 'Artistic & Organic',
    status: 'active',
    tagline: 'Architectural study, drafting vellum grid, and annotated designer thinking.',
    description: 'Warm vellum drafting grid, graphite ink rules, technical blue pen and revision red annotations, and diagrammatic concept composition.',
    accentColor: '#2563eb',
    previewGradient: 'linear-gradient(135deg, #faf8f3 0%, #2563eb 50%, #1f2124 100%)',
    features: ['Drafting vellum grid canvas', 'Graphite rules & framing', 'Hand-drawn notes & markers', 'Diagrammatic concept modules'],
  },
  {
    id: 'luxury-typography',
    name: 'Luxury Typography',
    category: 'Modern',
    status: 'active',
    tagline: 'Editorial high-fashion restraint, champagne hairlines, and typographic poise.',
    description: 'Monumental high-contrast Didone serifs, whisper-quiet uppercase sans, champagne accents, and generous editorial breathing room.',
    accentColor: '#c2a67e',
    previewGradient: 'linear-gradient(135deg, #121211 0%, #2b2826 100%)',
    features: ['Monumental Didone serifs', 'Whisper uppercase sans', 'Delicate hairlines', 'Warm luxury paper'],
  },
  {
    id: 'editorial-design',
    name: 'Editorial Design',
    category: 'Modern',
    status: 'active',
    tagline: 'Broadsheet publishing layout, authoritative serifs, and narrative visual pacing.',
    description: 'Journalistic story hierarchy, lede decks, bylines, broadsheet rules, drop-caps, and narrative reading rhythm.',
    accentColor: '#991b1b',
    previewGradient: 'linear-gradient(135deg, #141413 0%, #3f3f46 100%)',
    features: ['Broadsheet rules & rubrics', 'Authoritative serif headlines', 'Lede decks & bylines', 'Warm newsprint paper'],
  },
  {
    id: 'y2k-aesthetic',
    name: 'Y2K Aesthetic',
    category: 'Retro & Heritage',
    status: 'active',
    tagline: 'Year 2000 metallic chrome, bubbly translucency, and optimism.',
    description: 'Silver metallic gradients, futuristic bubble geometry, iridescent highlights, and early millennium techno-optimism.',
    accentColor: '#06b6d4',
    previewGradient: 'linear-gradient(135deg, #cffafe 0%, #e0e7ff 100%)',
    features: ['Chrome metallic gradients', 'Inflatable bubble buttons', 'Cyber techno fonts', 'Iridescent glares'],
  },
  {
    id: 'ethereal',
    name: 'Ethereal',
    category: 'Artistic & Organic',
    status: 'active',
    tagline: 'Atmospheric light, weightless typography, luminous pearl surfaces, and quiet serenity.',
    description: 'Luminous illuminated air foundation, delicate serifs, pearl surfaces, soft mist blue and pale lavender accents, and serene spacious hierarchy.',
    accentColor: '#818cf8',
    previewGradient: 'linear-gradient(135deg, #fbfaf8 0%, #e8eef5 50%, #f3f0f8 100%)',
    features: ['Illuminated air canvas', 'Weightless display typography', 'Luminous pearl surfaces', 'Serene atmospheric breathing room'],
  },
  {
    id: 'bohemian',
    name: 'Bohemian',
    category: 'Artistic & Organic',
    status: 'active',
    tagline: 'Warm terracotta, sun-baked clay, artisanal typography, and eclectic collected surfaces.',
    description: 'Warm cream and parchment foundations, expressive Fraunces display serifs, sun-baked terracotta and mustard accents, handcrafted organic geometry, and eclectic collected warmth.',
    accentColor: '#c85a32',
    previewGradient: 'linear-gradient(135deg, #fbf7ee 0%, #f4ece1 40%, #edd3ba 70%, #c85a32 100%)',
    features: ['Sun-baked terracotta & clay', 'Expressive Fraunces serifs', 'Handcrafted organic geometry', 'Collected eclectic variation'],
  },
  {
    id: 'dark-mode-ui',
    name: 'Dark Mode UI',
    category: 'Modern',
    status: 'active',
    tagline: 'Deep layered surfaces, controlled contrast, deliberate elevation, and professional dark polish.',
    description: 'Layered dark surfaces (#09090b, #111113, #18181b), subtle neutral borders, glare-free high-contrast typography, and restrained professional accents for comfortable long-session viewing.',
    accentColor: '#3b82f6',
    previewGradient: 'linear-gradient(135deg, #09090b 0%, #18181b 60%, #27272a 100%)',
    features: ['Layered surface hierarchy', 'Controlled contrast & glare-free', 'Subtle neutral borders', 'Restrained professional accents'],
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    category: 'Expressive',
    status: 'active',
    tagline: 'High-tech low-life neon, terminal glitches, and dark alleys.',
    description: 'Neon cyan and hot laser magenta glows against pitch-black alleyways, monospace telemetry, and angular hazard clips.',
    accentColor: '#00f0ff',
    previewGradient: 'linear-gradient(135deg, #050508 0%, #1a0826 100%)',
    features: ['Neon cyan & magenta glows', 'Monospaced telemetry HUD', 'Chamfered polygon cuts', 'High-contrast pitch dark'],
  },
  {
    id: 'anthropomorphic',
    name: 'Anthropomorphic',
    category: 'Artistic & Organic',
    status: 'active',
    tagline: 'Warm organic curves, conversational typography, and living personality.',
    description: 'A digital environment with personality: friendly organic geometry, springy reactive controls, conversational typography, and warm approachable accents.',
    accentColor: '#ff6b57',
    previewGradient: 'linear-gradient(135deg, #fff0ed 0%, #ffd6cf 50%, #fdfbf7 100%)',
    features: ['Organic asymmetrical curves', 'Living spring micro-interactions', 'Conversational typography', 'Warm friendly personality'],
  },
  {
    id: 'victorian',
    name: 'Victorian',
    category: 'Retro & Heritage',
    status: 'active',
    tagline: '19th-century typography, ornate editorial print, engraved rules, and botanical motifs.',
    description: 'Aged parchment paper, botanical forest green and imperial claret tones, Castoro Titling & EB Garamond typography, engraved double rules, and formal editorial framing.',
    accentColor: '#9e783e',
    previewGradient: 'linear-gradient(135deg, #1b3b2b 0%, #5c1626 50%, #f7f2e7 100%)',
    features: ['19th-century typography', 'Engraved printer rules', 'Aged parchment paper', 'Botanical forest & claret tones'],
  },
  {
    id: 'cybercore',
    name: 'Cybercore',
    category: 'Expressive',
    status: 'active',
    tagline: 'Internet-native digital culture, fragmented interfaces, corrupted media, and CRT artifacts.',
    description: 'Dark digital surfaces, selective CRT scanlines, technical monospace metadata, offset layer borders, and fragmented experimental interfaces.',
    accentColor: '#00ff66',
    previewGradient: 'linear-gradient(135deg, #0c0e12 0%, #1a202c 50%, #00ff66 100%)',
    features: ['Fragmented digital layers', 'Selective CRT scanlines', 'Technical monospace metadata', 'Offset layer borders'],
  },
  {
    id: 'art-deco',
    name: 'Art Deco',
    category: 'Retro & Heritage',
    status: 'active',
    tagline: 'Roaring 1920s geometric glamour, chevron zigzags, and metallic gold.',
    description: 'Symmetrical sunburst and chevron motifs, gleaming gold on black obsidian, architectural stepped crowns, and jazz age flair.',
    accentColor: '#d4af37',
    previewGradient: 'linear-gradient(135deg, #0e0e11 0%, #1c1a16 50%, #d4af37 100%)',
    features: ['Chevron & sunburst lines', 'Gleaming gold leaf accents', 'Stepped architectural rims', 'Gatsby typographic grandeur'],
  },
  {
    id: 'bauhaus',
    name: 'Bauhaus',
    category: 'Modern',
    status: 'active',
    tagline: 'Form follows function. Primary geometry, red, blue, and yellow.',
    description: 'Fundamental primary geometry (circle, square, triangle), stark red/yellow/blue palette, and functional clarity.',
    accentColor: '#d9261e',
    previewGradient: 'linear-gradient(135deg, #f7f5f0 0%, #d9261e 40%, #1b4f9b 80%, #f2b705 100%)',
    features: ['Primary color palette', 'Circle, square & triangle forms', 'Functional typography', 'Radical geometric purity'],
  },
  {
    id: 'wabi-sabi',
    name: 'Wabi-Sabi',
    category: 'Artistic & Organic',
    status: 'active',
    tagline: 'Beauty in imperfection, washi paper, natural stoneware, and peaceful asymmetry.',
    description: 'Warm washi paper canvas, earthy sumi ink, subtle stoneware textures, organic asymmetry, matcha accents, and quiet tranquil mindfulness.',
    accentColor: '#4d7c0f',
    previewGradient: 'linear-gradient(135deg, #f7f4ee 0%, #eeeae0 50%, #4d7c0f 100%)',
    features: ['Washi paper warmth', 'Sumi ink typography', 'Stoneware organic texture', 'Tranquil meditative space'],
  },
  {
    id: 'synthwave',
    name: 'Synthwave',
    category: 'Retro & Heritage',
    status: 'active',
    tagline: '1980s neon sunset, retro wireframe horizon grid, and arcade synthesizers.',
    description: 'Deep midnight purple void, outrun sunset gradients, arcade neon glows, wireframe horizon grids, and wide retro-futuristic typography.',
    accentColor: '#ff2a85',
    previewGradient: 'linear-gradient(135deg, #0f051d 0%, #250e49 45%, #ff2a85 85%, #01cdfe 100%)',
    features: ['Neon sunset gradients', 'Perspective horizon grid', 'Wide retro-futurist type', 'Arcade neon luminous glow'],
  },
  {
    id: 'solarpunk',
    name: 'Solarpunk',
    category: 'Artistic & Organic',
    status: 'upcoming',
    tagline: 'Art Nouveau stained glass, renewable ecology, and sunlit brass.',
    description: 'Lush botanical curves, stained-glass light refractions, warm polished brass, verdant leaves, and an optimistic ecological future.',
    accentColor: '#10b981',
    previewGradient: 'linear-gradient(135deg, #ecfdf5 0%, #fef3c7 100%)',
    features: ['Art Nouveau organic curves', 'Stained glass light refractions', 'Verdant leaf & floral motifs', 'Warm sunlit brass accents'],
  },
  {
    id: 'graffiti',
    name: 'Graffiti',
    category: 'Expressive',
    status: 'active',
    tagline: 'Street art murals, spray paint textures, tag lettering, and urban visual rebellion.',
    description: 'Concrete/asphalt surfaces, raw marker strokes, stencil typography, sticker badges, spray paint spatters, and high-energy urban visual culture.',
    accentColor: '#ff1e42',
    previewGradient: 'linear-gradient(135deg, #121214 0%, #26272e 45%, #ff1e42 85%, #ffea00 100%)',
    features: ['Spray paint textures', 'Die-cut sticker badges', 'Bold stencil & tag typography', 'Layered wheatpaste posters'],
  },
  {
    id: 'gothic',
    name: 'Gothic',
    category: 'Retro & Heritage',
    status: 'active',
    tagline: 'Medieval cathedral architecture, illuminated manuscripts, antique brass rules, and dark romanticism.',
    description: 'Deep cathedral stone, aged vellum ivory, antique brass rules, pointed lancet arch profiles, illuminated manuscript drop caps, and dramatic monumental serifs.',
    accentColor: '#c5a059',
    previewGradient: 'linear-gradient(135deg, #0c0c0e 0%, #151518 45%, #631326 80%, #c5a059 100%)',
    features: ['Lancet arch card profiles', 'Illuminated manuscript drop caps', 'Antique brass ecclesiastical rules', 'Monumental Cinzel & Garamond typography'],
  },
  {
    id: 'mixed-media',
    name: 'Mixed Media',
    category: 'Artistic & Organic',
    status: 'active',
    tagline: 'Art-directed collage of photography, paper textures, editorial serifs, paint marks, and geometric vector lines.',
    description: 'Curated gallery of physical and artistic media: cotton rag paper canvas, vermilion ink marks, editorial serif and modernist sans typography, matted photo frames, and deliberate geometric overlays.',
    accentColor: '#e63926',
    previewGradient: 'linear-gradient(135deg, #f8f6f0 0%, #f1ede4 45%, #1a1918 80%, #e63926 100%)',
    features: ['Cotton rag paper foundation', 'Editorial serif & modernist sans', 'Painterly ink wash & paint strokes', 'Geometric vector framing marks'],
  },
];
