import {
  brutalistSemanticCss,
  minimalistSemanticCss,
  glassmorphismSemanticCss,
  maximalistSemanticCss,
  swissDesignSemanticCss,
  surrealDesignSemanticCss,
  neoBrutalistSemanticCss,
  neoClassicalSemanticCss,
  luxuryTypographySemanticCss,
  editorialDesignSemanticCss,
  y2kAestheticSemanticCss,
  bentoGridSemanticCss,
  pixelArtSemanticCss,
  conceptualSketchSemanticCss,
  etherealSemanticCss,
  bohemianSemanticCss,
  cyberpunkSemanticCss,
  anthropomorphicSemanticCss,
  neumorphicSemanticCss,
  darkModeUiSemanticCss,
  scrapbookSemanticCss,
  claymorphicSemanticCss,
  victorianSemanticCss,
  cybercoreSemanticCss,
  synthwaveSemanticCss,
  graffitiSemanticCss,
  gothicSemanticCss,
  mixedMediaSemanticCss,
  artDecoSemanticCss,
  bauhausSemanticCss,
  solarpunkSemanticCss,
  wabiSabiSemanticCss,
} from './index';

export const SEMANTIC_CSS_MAP: Record<string, string> = {
  'brutalism': brutalistSemanticCss,
  'minimalism': minimalistSemanticCss,
  'glassmorphism': glassmorphismSemanticCss,
  'maximalism': maximalistSemanticCss,
  'swiss-design': swissDesignSemanticCss,
  'surrealism': surrealDesignSemanticCss,
  'neo-brutalism': neoBrutalistSemanticCss,
  'neo-classical': neoClassicalSemanticCss,
  'luxury-typography': luxuryTypographySemanticCss,
  'editorial-design': editorialDesignSemanticCss,
  'y2k-aesthetic': y2kAestheticSemanticCss,
  'bento-grid': bentoGridSemanticCss,
  'pixel-art': pixelArtSemanticCss,
  'conceptual-sketch': conceptualSketchSemanticCss,
  'ethereal': etherealSemanticCss,
  'bohemian': bohemianSemanticCss,
  'cyberpunk': cyberpunkSemanticCss,
  'anthropomorphic': anthropomorphicSemanticCss,
  'neumorphism': neumorphicSemanticCss,
  'dark-mode-ui': darkModeUiSemanticCss,
  'scrapbook': scrapbookSemanticCss,
  'claymorphism': claymorphicSemanticCss,
  'victorian': victorianSemanticCss,
  'cybercore': cybercoreSemanticCss,
  'synthwave': synthwaveSemanticCss,
  'graffiti': graffitiSemanticCss,
  'gothic': gothicSemanticCss,
  'mixed-media': mixedMediaSemanticCss,
  'art-deco': artDecoSemanticCss,
  'bauhaus': bauhausSemanticCss,
  'solarpunk': solarpunkSemanticCss,
  'wabi-sabi': wabiSabiSemanticCss,
};
