import { StyleDefinition } from '../../core/types/style-definition';

export const bentoGridStyle: StyleDefinition = {
  id: 'bento-grid',
  name: 'Bento Grid',
  description: 'Modular, compartmentalized content packaging with varied spatial hierarchy, modern geometry, and high density.',
  metadata: {
    version: '1.0.0',
    category: 'Modern',
    tags: ['bento-grid', 'modular', 'asymmetric', 'spatial-hierarchy', 'modern', 'layout'],
  },
  tokens: {
    colors: {
      background: '#f8fafc', // Modern neutral slate
      surface: '#ffffff', // Clean modular tile
      surfaceSubtle: '#f1f5f9',
      textPrimary: '#0f172a', // Deep slate ink
      textSecondary: '#475569',
      textMuted: '#94a3b8',
      primary: '#4f46e5', // Rich indigo accent
      primaryHover: '#4338ca',
      primaryText: '#ffffff',
      accent: '#6366f1',
      border: '#e2e8f0', // Clean 1px hairline border
      borderStrong: '#cbd5e1',
      ring: 'rgba(79, 70, 229, 0.25)',
    },
    typography: {
      fontFamilyBase: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      fontFamilyHeading: "'Plus Jakarta Sans', 'Inter', -apple-system, sans-serif",
      fontFamilyMono: "'JetBrains Mono', monospace",
      fontSizeXs: '0.75rem',
      fontSizeSm: '0.875rem',
      fontSizeBase: '1rem',
      fontSizeLg: '1.25rem',
      fontSizeXl: '2rem',
      fontSize2xl: '3rem',
      fontWeightNormal: 400,
      fontWeightMedium: 600,
      fontWeightBold: 800,
      lineHeightBase: 1.65,
      lineHeightHeading: 1.1,
      letterSpacingBase: '-0.01em',
      letterSpacingHeading: '-0.035em',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1.25rem',
      lg: '2rem',
      xl: '3.5rem',
      '2xl': '5rem',
    },
    radii: {
      none: '0px',
      sm: '8px',
      md: '18px',
      lg: '22px',
      full: '9999px',
    },
    borders: {
      widthThin: '1px',
      widthBase: '1px',
      widthThick: '2px',
      style: 'solid',
    },
    shadows: {
      none: 'none',
      sm: '0 1px 3px rgba(15, 23, 42, 0.04)',
      md: '0 4px 20px -2px rgba(15, 23, 42, 0.04)',
      lg: '0 12px 32px -4px rgba(15, 23, 42, 0.08)',
      glow: '0 0 20px rgba(79, 70, 229, 0.25)',
    },
    motion: {
      durationFast: '120ms',
      durationNormal: '180ms',
      easing: 'ease',
    },
    effects: {
      backdropBlur: '12px',
      transformHover: 'translateY(-2px)',
    },
  },
  components: {
    button: {
      padding: '0.75rem 1.65rem',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '0.875rem',
      fontWeight: 600,
      letterSpacing: '-0.01em',
      textTransform: 'none',
      borderRadius: '12px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#0f172a',
      background: '#0f172a',
      color: '#ffffff',
      boxShadow: '0 4px 12px rgba(15, 23, 42, 0.12)',
      transition: 'all 160ms ease',
      hover: {
        background: '#4f46e5',
        borderColor: '#4f46e5',
        color: '#ffffff',
      },
      active: {
        background: '#4338ca',
        borderColor: '#4338ca',
      },
      focusRing: '0 0 0 3px rgba(79, 70, 229, 0.25)',
    },
    card: {
      padding: '2rem',
      borderRadius: '20px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#e2e8f0',
      background: '#ffffff',
      color: '#0f172a',
      boxShadow: '0 4px 20px -2px rgba(15, 23, 42, 0.04)',
      transition: 'all 180ms ease',
      hover: {
        borderColor: 'rgba(79, 70, 229, 0.3)',
      },
    },
    heading: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontWeight: 800,
      letterSpacing: '-0.035em',
      lineHeight: 1.1,
      color: '#0f172a',
    },
    paragraph: {
      fontFamily: "'Inter', sans-serif",
      fontSize: '1rem',
      lineHeight: 1.65,
      color: '#475569',
    },
    input: {
      padding: '0.75rem 1.15rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.9375rem',
      borderRadius: '12px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#e2e8f0',
      background: '#f8fafc',
      color: '#0f172a',
      placeholderColor: '#94a3b8',
      focusBorderColor: '#4f46e5',
      focusRing: '0 0 0 3px rgba(79, 70, 229, 0.15)',
      transition: 'all 160ms ease',
    },
    badge: {
      padding: '0.35rem 0.85rem',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '0.75rem',
      fontWeight: 700,
      letterSpacing: '0.06em',
      textTransform: 'uppercase',
      borderRadius: '9999px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: 'rgba(79, 70, 229, 0.18)',
      background: 'rgba(79, 70, 229, 0.08)',
      color: '#4f46e5',
    },
    section: {
      padding: '4.5rem 2rem',
      background: 'transparent',
      borderColor: '#e2e8f0',
      borderWidth: '1px',
      borderStyle: 'none',
    },
    page: {
      background: '#f8fafc',
      color: '#0f172a',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
    },
  },
};

export { bentoGridSemanticCss } from './rules';
