import { StyleDefinition } from '../../core/types/style-definition';

export const neoClassicalStyle: StyleDefinition = {
  id: 'neo-classical',
  name: 'Neo-Classical',
  description: 'Classical architectural proportion, editorial serif refinement, structured rules, plinth bases, and dignified restraint.',
  metadata: {
    version: '1.0.0',
    category: 'Retro & Heritage',
    tags: ['neo-classical', 'architectural', 'proportional', 'editorial-serif', 'refined', 'symmetry', 'restraint'],
  },
  tokens: {
    colors: {
      background: '#fcfbf7', // Warm ivory parchment paper
      surface: '#ffffff',
      surfaceSubtle: '#f7f4ee',
      textPrimary: '#1a1917', // Deep architectural charcoal ink
      textSecondary: '#4a4742',
      textMuted: '#8c857b',
      primary: '#1a1917',
      primaryHover: '#302d28',
      primaryText: '#fcfbf7',
      accent: '#b89758', // Restrained antique brass
      border: '#ded8ce', // Stone hairline
      borderStrong: '#1a1917',
      ring: 'rgba(184, 151, 88, 0.35)',
    },
    typography: {
      fontFamilyBase: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      fontFamilyHeading: "'Cinzel', 'Playfair Display', 'Cormorant Garamond', 'Baskerville', 'Georgia', serif",
      fontFamilyMono: "'JetBrains Mono', monospace",
      fontSizeXs: '0.6875rem',
      fontSizeSm: '0.8125rem',
      fontSizeBase: '1rem',
      fontSizeLg: '1.25rem',
      fontSizeXl: '1.85rem',
      fontSize2xl: '2.75rem',
      fontWeightNormal: 400,
      fontWeightMedium: 600,
      fontWeightBold: 700,
      lineHeightBase: 1.7,
      lineHeightHeading: 1.15,
      letterSpacingBase: '0em',
      letterSpacingHeading: '0.02em',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1.25rem',
      lg: '2.5rem',
      xl: '4rem',
      '2xl': '6rem',
    },
    radii: {
      none: '0px',
      sm: '2px', // Crisp architectural geometry
      md: '4px',
      lg: '6px',
      full: '9999px',
    },
    borders: {
      widthThin: '1px',
      widthBase: '1px',
      widthThick: '2px',
      style: 'solid',
    },
    shadows: {
      none: 'none',
      sm: '0 2px 8px rgba(26, 25, 23, 0.04)',
      md: '0 4px 16px rgba(26, 25, 23, 0.06)',
      lg: '0 8px 24px rgba(26, 25, 23, 0.08)',
      glow: 'none',
    },
    motion: {
      durationFast: '140ms',
      durationNormal: '220ms',
      easing: 'cubic-bezier(0.2, 0, 0, 1)',
    },
    effects: {
      backdropBlur: 'none',
      transformHover: 'none',
    },
  },
  components: {
    button: {
      padding: '0.9rem 2.25rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.78125rem',
      fontWeight: 600,
      letterSpacing: '0.16em',
      textTransform: 'uppercase',
      borderRadius: '2px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#1a1917',
      background: '#1a1917',
      color: '#fcfbf7',
      boxShadow: 'none',
      transition: 'all 180ms ease',
      hover: {
        background: '#302d28',
        borderColor: '#302d28',
        color: '#ffffff',
      },
      active: {
        background: '#1a1917',
        borderColor: '#1a1917',
      },
      focusRing: '0 0 0 2px rgba(184, 151, 88, 0.4)',
    },
    card: {
      padding: '2.75rem 2rem',
      borderRadius: '2px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#ded8ce',
      background: '#ffffff',
      color: '#1a1917',
      boxShadow: 'none',
      transition: 'border-color 180ms ease',
      hover: {
        borderColor: '#1a1917',
      },
    },
    heading: {
      fontFamily: "'Cinzel', 'Playfair Display', 'Cormorant Garamond', 'Georgia', serif",
      fontWeight: 600,
      letterSpacing: '0.02em',
      lineHeight: 1.15,
      color: '#1a1917',
    },
    paragraph: {
      fontFamily: "'Inter', -apple-system, sans-serif",
      fontSize: '1.03125rem',
      lineHeight: 1.75,
      color: '#383531',
    },
    input: {
      padding: '0.85rem 1.15rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.9375rem',
      borderRadius: '2px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#ded8ce',
      background: '#ffffff',
      color: '#1a1917',
      placeholderColor: '#8c857b',
      focusBorderColor: '#1a1917',
      focusRing: 'none',
      transition: 'border-color 160ms ease',
    },
    badge: {
      padding: '0.35rem 0.85rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.6875rem',
      fontWeight: 700,
      letterSpacing: '0.2em',
      textTransform: 'uppercase',
      borderRadius: '2px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#ded8ce',
      background: '#f7f4ee',
      color: '#1a1917',
    },
    section: {
      padding: '4.5rem 2rem',
      background: 'transparent',
      borderColor: '#ded8ce',
      borderWidth: '1px',
      borderStyle: 'none',
    },
    page: {
      background: '#fcfbf7',
      color: '#1a1917',
      fontFamily: "'Inter', -apple-system, sans-serif",
    },
  },
};

export { neoClassicalSemanticCss } from './rules';
