import { StyleDefinition } from '../../core/types/style-definition';

export const maximalismStyle: StyleDefinition = {
  id: 'maximalism',
  name: 'Maximalism',
  description: 'Rich, layered, expressive visual density with curated royal crimson and saffron accents, tactile parchment foundation, and expressive display serif typography.',
  metadata: {
    version: '1.0.0',
    category: 'Expressive',
    tags: ['maximalism', 'layered', 'density', 'ornament', 'expressive', 'serif', 'tactile', 'abundance'],
  },
  tokens: {
    colors: {
      background: '#faf6ef', // Tactile warm ivory / parchment
      surface: '#fffdf9',
      surfaceSubtle: '#f7f1e7',
      textPrimary: '#18130f', // Deep espresso ink
      textSecondary: '#4a3e35',
      textMuted: '#786b5f',
      primary: '#701a2b', // Royal crimson
      primaryHover: '#881337',
      primaryText: '#ffffff',
      accent: '#d97706', // Metallic amber saffron
      border: '#dcd2be',
      borderStrong: '#18130f',
      ring: 'rgba(112, 26, 43, 0.35)',
    },
    typography: {
      fontFamilyBase: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
      fontFamilyHeading: "'Playfair Display', Georgia, serif",
      fontFamilyMono: "'JetBrains Mono', monospace",
      fontSizeXs: '0.75rem',
      fontSizeSm: '0.875rem',
      fontSizeBase: '1.03125rem',
      fontSizeLg: '1.25rem',
      fontSizeXl: '1.85rem',
      fontSize2xl: '2.75rem',
      fontWeightNormal: 400,
      fontWeightMedium: 600,
      fontWeightBold: 800,
      lineHeightBase: 1.65,
      lineHeightHeading: 1.15,
      letterSpacingBase: '-0.005em',
      letterSpacingHeading: '-0.02em',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1rem',
      lg: '1.75rem',
      xl: '2.75rem',
      '2xl': '4.5rem',
    },
    radii: {
      none: '0px',
      sm: '2px',
      md: '4px',
      lg: '6px',
      full: '9999px',
    },
    borders: {
      widthThin: '1px',
      widthBase: '2px',
      widthThick: '4px',
      style: 'solid',
    },
    shadows: {
      none: 'none',
      sm: '2px 2px 0px #18130f',
      md: '3px 3px 0px #18130f',
      lg: '5px 5px 0px #18130f',
      glow: '0 0 15px rgba(217, 119, 6, 0.3)',
    },
    motion: {
      durationFast: '120ms',
      durationNormal: '200ms',
      easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    },
    effects: {
      backdropBlur: 'none',
      transformHover: 'translate(-1px, -1px)',
    },
  },
  components: {
    button: {
      padding: '0.8rem 1.75rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.875rem',
      fontWeight: 700,
      borderRadius: '3px',
      borderWidth: '2px',
      borderStyle: 'solid',
      borderColor: '#18130f',
      background: 'linear-gradient(180deg, #831843 0%, #701a2b 100%)',
      color: '#ffffff',
      boxShadow: '3px 3px 0px #18130f',
      textTransform: 'uppercase',
      letterSpacing: '0.08em',
      transition: 'transform 120ms ease, box-shadow 120ms ease, background 120ms ease',
      hover: {
        background: 'linear-gradient(180deg, #9f1239 0%, #881337 100%)',
        transform: 'translate(-1px, -1px)',
        boxShadow: '4px 4px 0px #18130f',
      },
      active: {
        transform: 'translate(2px, 2px)',
        boxShadow: '1px 1px 0px #18130f',
      },
      focusRing: '0 0 0 3px rgba(112, 26, 43, 0.4)',
    },
    card: {
      padding: '1.75rem',
      borderRadius: '3px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#dcd2be',
      background: '#fffdf9',
      color: '#18130f',
      boxShadow: '3px 3px 0px rgba(24, 19, 15, 0.08)',
      transition: 'transform 160ms ease, box-shadow 160ms ease',
      hover: {
        transform: 'translateY(-2px)',
        boxShadow: '4px 4px 0px rgba(24, 19, 15, 0.14)',
      },
    },
    heading: {
      fontFamily: "'Playfair Display', Georgia, serif",
      fontWeight: 800,
      letterSpacing: '-0.02em',
      lineHeight: 1.15,
      color: '#18130f',
    },
    paragraph: {
      fontFamily: "'Inter', sans-serif",
      fontSize: '1.03125rem',
      lineHeight: 1.7,
      color: '#2c241e',
    },
    input: {
      padding: '0.8rem 1.1rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.9375rem',
      borderRadius: '3px',
      borderWidth: '2px',
      borderStyle: 'solid',
      borderColor: '#c8baa8',
      background: '#fffdf9',
      color: '#18130f',
      placeholderColor: '#9e8f7f',
      focusBorderColor: '#701a2b',
      focusRing: '3px 3px 0px #701a2b',
      transition: 'border-color 120ms ease, box-shadow 120ms ease',
    },
    badge: {
      padding: '0.25rem 0.65rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.75rem',
      fontWeight: 800,
      textTransform: 'uppercase',
      letterSpacing: '0.12em',
      borderRadius: '2px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#701a2b',
      background: 'rgba(112, 26, 43, 0.08)',
      color: '#701a2b',
    },
    section: {
      padding: '3rem 2rem',
      background: 'transparent',
      borderColor: '#dcd2be',
      borderWidth: '1px',
      borderStyle: 'none',
    },
    page: {
      background: '#faf6ef',
      color: '#18130f',
      fontFamily: "'Inter', sans-serif",
    },
  },
};

export { maximalistSemanticCss } from './rules';
