import { StyleDefinition } from '../../core/types/style-definition';

export const brutalismStyle: StyleDefinition = {
  id: 'brutalism',
  name: 'Brutalism',
  description: 'Uncompromising, high-contrast aesthetic featuring stark 3px solid black borders, 0px sharp corners, bold tactile offset drop shadows, uppercase typography, and electric neo-acid highlights.',
  metadata: {
    version: '1.0.0',
    category: 'Expressive',
    tags: ['brutalism', 'bold', 'raw', 'high-contrast', 'neo-brutalist', 'geometric'],
  },
  tokens: {
    colors: {
      background: '#f4f3ed', // Raw concrete/newsprint tone
      surface: '#ffffff',
      surfaceSubtle: '#eae8dc', // Refined architectural concrete tint (not blinding yellow)
      textPrimary: '#000000',
      textSecondary: '#1a1a1a',
      textMuted: '#555555',
      primary: '#ffe600', // Iconic acid yellow reserved for accents and primary interactions
      primaryHover: '#fff04d',
      primaryText: '#000000',
      accent: '#ff2a5f', // Shocking crimson
      border: '#000000',
      borderStrong: '#000000',
      ring: '#000000',
    },
    typography: {
      fontFamilyBase: "'Space Grotesk', -apple-system, sans-serif",
      fontFamilyHeading: "'Space Grotesk', -apple-system, sans-serif",
      fontFamilyMono: "'JetBrains Mono', monospace",
      fontSizeXs: '0.75rem',
      fontSizeSm: '0.875rem',
      fontSizeBase: '1rem',
      fontSizeLg: '1.25rem',
      fontSizeXl: '1.75rem',
      fontSize2xl: '2.5rem',
      fontWeightNormal: 500,
      fontWeightMedium: 700,
      fontWeightBold: 800,
      lineHeightBase: 1.55,
      lineHeightHeading: 1.15,
      letterSpacingBase: '0em',
      letterSpacingHeading: '-0.02em',
    },
    spacing: {
      xs: '0.35rem',
      sm: '0.75rem',
      md: '1.25rem',
      lg: '2rem',
      xl: '3rem',
      '2xl': '4.5rem',
    },
    radii: {
      none: '0px',
      sm: '0px',
      md: '0px',
      lg: '0px',
      full: '0px', // Uncompromising zero radius
    },
    borders: {
      widthThin: '2px',
      widthBase: '3px',
      widthThick: '4px',
      style: 'solid',
    },
    shadows: {
      none: 'none',
      sm: '3px 3px 0px #000000',
      md: '5px 5px 0px #000000',
      lg: '8px 8px 0px #000000',
      glow: '0px 0px 0px 3px #000000',
    },
    motion: {
      durationFast: '80ms',
      durationNormal: '150ms',
      easing: 'cubic-bezier(0, 0, 0.2, 1)',
    },
    effects: {
      backdropBlur: 'none',
      transformHover: 'translate(-2px, -2px)',
    },
  },
  components: {
    button: {
      padding: '0.75rem 1.5rem',
      fontFamily: "'Space Grotesk', sans-serif",
      fontSize: '0.875rem',
      fontWeight: 800,
      letterSpacing: '0.05em',
      textTransform: 'uppercase',
      borderRadius: '0px',
      borderWidth: '3px',
      borderStyle: 'solid',
      borderColor: '#000000',
      background: '#ffe600',
      color: '#000000',
      boxShadow: '4px 4px 0px #000000',
      transition: 'transform 80ms ease, box-shadow 80ms ease, background 80ms ease',
      hover: {
        background: '#fff04d',
        transform: 'translate(-2px, -2px)',
        boxShadow: '6px 6px 0px #000000',
      },
      active: {
        transform: 'translate(2px, 2px)',
        boxShadow: '1px 1px 0px #000000',
      },
      focusRing: '0 0 0 3px #000000',
    },
    card: {
      padding: '1.75rem',
      borderRadius: '0px',
      borderWidth: '3px',
      borderStyle: 'solid',
      borderColor: '#000000',
      background: '#ffffff',
      color: '#000000',
      boxShadow: '5px 5px 0px #000000',
      transition: 'transform 100ms ease, box-shadow 100ms ease',
      hover: {
        transform: 'translate(-2px, -2px)',
        boxShadow: '7px 7px 0px #000000',
      },
    },
    heading: {
      fontFamily: "'Space Grotesk', sans-serif",
      fontWeight: 800,
      letterSpacing: '-0.02em',
      lineHeight: 1.15,
      color: '#000000',
      textTransform: 'none',
    },
    paragraph: {
      fontFamily: "'Space Grotesk', sans-serif",
      fontSize: '1rem',
      lineHeight: 1.6,
      color: '#1a1a1a',
    },
    input: {
      padding: '0.75rem 1rem',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '0.9375rem',
      borderRadius: '0px',
      borderWidth: '2.5px',
      borderStyle: 'solid',
      borderColor: '#000000',
      background: '#ffffff',
      color: '#000000',
      placeholderColor: '#666666',
      boxShadow: '3px 3px 0px #000000',
      focusBorderColor: '#000000',
      focusRing: '0 0 0 2px #ffe600',
      transition: 'box-shadow 100ms ease',
    },
    badge: {
      padding: '0.25rem 0.625rem',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '0.75rem',
      fontWeight: 700,
      letterSpacing: '0.06em',
      textTransform: 'uppercase',
      borderRadius: '0px',
      borderWidth: '2px',
      borderStyle: 'solid',
      borderColor: '#000000',
      background: '#ffe600',
      color: '#000000',
      boxShadow: '2px 2px 0px #000000',
    },
    section: {
      padding: '3rem 2rem',
      background: '#f4f3ed',
      borderColor: '#000000',
      borderWidth: '3px',
      borderStyle: 'solid',
    },
    page: {
      background: '#f4f3ed',
      color: '#000000',
      fontFamily: "'Space Grotesk', sans-serif",
    },
  },
};

export { brutalistSemanticCss } from './rules';

