import { StyleDefinition } from '../../core/types/style-definition';

export const neumorphismStyle: StyleDefinition = {
  id: 'neumorphism',
  name: 'Neumorphism',
  description: 'Soft extruded monochromatic surfaces, tactile depth, subtle light/shadow relationships, and physical interface controls molded from one continuous material.',
  metadata: {
    version: '1.0.0',
    category: 'Material & Depth',
    tags: ['neumorphism', 'soft-ui', 'tactile', 'extruded', 'monochromatic', 'shadows', 'material'],
  },
  compositionConfig: {
    containerPhilosophy: 'soft-extruded',
    groupingPhilosophy: 'tactile-cluster',
    featurePresentation: 'extruded-card',
    heroMode: 'open-canvas',
    maxWidth: '1200px',
    alignment: 'clean-grid',
    density: 'comfortable',
    hasStructuralBorders: false,
    hasAsymmetricOffsets: false,
    hasDecorativeFraming: false,
  },
  tokens: {
    colors: {
      background: '#e0e5ec', // Soft continuous neutral base
      surface: '#e0e5ec', // Continuous molded surface
      surfaceSubtle: '#d7dde5',
      textPrimary: '#1e293b', // High-contrast slate charcoal (10.4:1 contrast ratio)
      textSecondary: '#475569',
      textMuted: '#64748b',
      primary: '#3b82f6', // Tactile soft cobalt accent
      primaryHover: '#2563eb',
      primaryText: '#1e293b',
      accent: '#3b82f6',
      border: 'rgba(163, 177, 198, 0.3)',
      borderStrong: 'rgba(163, 177, 198, 0.6)',
      ring: 'rgba(59, 130, 246, 0.35)',
    },
    typography: {
      fontFamilyBase: "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      fontFamilyHeading: "'Plus Jakarta Sans', sans-serif",
      fontFamilyMono: "'JetBrains Mono', monospace",
      fontSizeXs: '0.75rem',
      fontSizeSm: '0.875rem',
      fontSizeBase: '1rem',
      fontSizeLg: '1.25rem',
      fontSizeXl: '1.85rem',
      fontSize2xl: '2.5rem',
      fontWeightNormal: 400,
      fontWeightMedium: 600,
      fontWeightBold: 800,
      lineHeightBase: 1.65,
      lineHeightHeading: 1.2,
      letterSpacingBase: '-0.01em',
      letterSpacingHeading: '-0.025em',
    },
    spacing: {
      xs: '0.35rem',
      sm: '0.75rem',
      md: '1.5rem',
      lg: '2.5rem',
      xl: '4rem',
      '2xl': '6rem',
    },
    radii: {
      none: '0px',
      sm: '10px',
      md: '16px',
      lg: '24px',
      full: '9999px',
    },
    borders: {
      widthThin: '0px',
      widthBase: '0px',
      widthThick: '1px',
      style: 'none',
    },
    shadows: {
      none: 'none',
      sm: '4px 4px 8px rgba(163, 177, 198, 0.55), -4px -4px 8px rgba(255, 255, 255, 0.9)',
      md: '7px 7px 15px rgba(163, 177, 198, 0.6), -7px -7px 15px rgba(255, 255, 255, 0.95)',
      lg: '10px 10px 22px rgba(163, 177, 198, 0.65), -10px -10px 22px rgba(255, 255, 255, 1)',
      glow: '0 0 20px rgba(59, 130, 246, 0.25)',
    },
    motion: {
      durationFast: '120ms',
      durationNormal: '200ms',
      easing: 'ease',
    },
    effects: {
      backdropBlur: 'none',
      transformHover: 'translateY(-1px)',
    },
  },
  components: {
    button: {
      padding: '0.8rem 1.75rem',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '0.9375rem',
      fontWeight: 700,
      letterSpacing: '-0.01em',
      borderRadius: '14px',
      borderWidth: '0px',
      borderStyle: 'solid',
      borderColor: 'transparent',
      background: '#e0e5ec',
      color: '#1e293b',
      boxShadow: '5px 5px 12px rgba(163, 177, 198, 0.65), -5px -5px 12px rgba(255, 255, 255, 0.95)',
      transition: 'all 180ms ease',
      hover: {
        background: '#e0e5ec',
        color: '#3b82f6',
        borderColor: 'transparent',
        boxShadow: '7px 7px 16px rgba(163, 177, 198, 0.75), -7px -7px 16px #ffffff',
      },
      active: {
        background: '#e0e5ec',
        color: '#2563eb',
        borderColor: 'transparent',
      },
      focusRing: '0 0 0 3px rgba(59, 130, 246, 0.4)',
    },
    card: {
      padding: '1.85rem',
      borderRadius: '16px',
      borderWidth: '0px',
      borderStyle: 'solid',
      borderColor: 'transparent',
      background: '#e0e5ec',
      color: '#1e293b',
      boxShadow: '7px 7px 15px rgba(163, 177, 198, 0.6), -7px -7px 15px rgba(255, 255, 255, 0.95)',
      transition: 'all 220ms ease',
      hover: {
        borderColor: 'transparent',
      },
    },
    input: {
      padding: '0.8rem 1.15rem',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '0.95rem',
      borderRadius: '12px',
      borderWidth: '0px',
      borderStyle: 'solid',
      borderColor: 'transparent',
      background: '#e0e5ec',
      color: '#1e293b',
      placeholderColor: '#64748b',
      focusBorderColor: 'transparent',
      focusRing: '0 0 0 3px rgba(59, 130, 246, 0.35)',
      transition: 'all 180ms ease',
    },
    heading: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      color: '#1e293b',
      fontWeight: 800,
      lineHeight: 1.2,
      letterSpacing: '-0.025em',
    },
    paragraph: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      color: '#475569',
      fontSize: '1rem',
      lineHeight: 1.65,
    },
    badge: {
      padding: '0.35rem 0.95rem',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '0.8125rem',
      fontWeight: 700,
      letterSpacing: '0.04em',
      textTransform: 'uppercase',
      borderRadius: '9999px',
      borderWidth: '0px',
      borderStyle: 'solid',
      borderColor: 'transparent',
      background: '#e0e5ec',
      color: '#64748b',
    },
    section: {
      padding: '3rem 2rem',
      background: '#e0e5ec',
      borderColor: 'transparent',
      borderWidth: '0px',
      borderStyle: 'none',
    },
    page: {
      background: '#e0e5ec',
      color: '#1e293b',
      fontFamily: "'Plus Jakarta Sans', -apple-system, sans-serif",
    },
  },
};

export { neumorphicSemanticCss } from './rules';
