import { StyleDefinition } from '../../core/types/style-definition';

export const swissDesignStyle: StyleDefinition = {
  id: 'swiss-design',
  name: 'Swiss Design',
  description: 'Rigorous mathematical grid clarity, asymmetrical layout hierarchies, authoritative objective sans-serif typography, stark Swiss Red (#dc2626) accents, and disciplined 1px architectural rules.',
  metadata: {
    version: '1.0.0',
    category: 'Modern',
    tags: ['swiss', 'international-style', 'grid', 'objective', 'asymmetric', 'helvetica', 'discipline'],
  },
  tokens: {
    colors: {
      background: '#ffffff', // Pure stark objective white
      surface: '#ffffff',
      surfaceSubtle: '#fafafa',
      textPrimary: '#000000', // Jet black
      textSecondary: '#52525b',
      textMuted: '#71717a',
      primary: '#ef4444', // Iconic International Swiss Red
      primaryHover: '#dc2626',
      primaryText: '#ffffff',
      accent: '#000000',
      border: '#000000',
      borderStrong: '#000000',
      ring: 'rgba(239, 68, 68, 0.35)',
    },
    typography: {
      fontFamilyBase: "'Helvetica Neue', Helvetica, 'Inter', Arial, sans-serif",
      fontFamilyHeading: "'Helvetica Neue', Helvetica, 'Inter', Arial, sans-serif",
      fontFamilyMono: "'JetBrains Mono', monospace",
      fontSizeXs: '0.75rem',
      fontSizeSm: '0.8125rem',
      fontSizeBase: '1rem',
      fontSizeLg: '1.25rem',
      fontSizeXl: '1.75rem',
      fontSize2xl: '2.5rem',
      fontWeightNormal: 400,
      fontWeightMedium: 600,
      fontWeightBold: 900, // Maximum typographic weight contrast
      lineHeightBase: 1.55,
      lineHeightHeading: 1.05,
      letterSpacingBase: '-0.015em',
      letterSpacingHeading: '-0.04em',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1rem',
      lg: '2rem',
      xl: '3rem',
      '2xl': '4.5rem',
    },
    radii: {
      none: '0px',
      sm: '0px',
      md: '0px',
      lg: '0px',
      full: '0px',
    },
    borders: {
      widthThin: '1px',
      widthBase: '1px',
      widthThick: '2px',
      style: 'solid',
    },
    shadows: {
      none: 'none',
      sm: 'none',
      md: 'none',
      lg: 'none',
      glow: 'none',
    },
    motion: {
      durationFast: '100ms',
      durationNormal: '150ms',
      easing: 'cubic-bezier(0, 0, 0.2, 1)',
    },
    effects: {
      backdropBlur: 'none',
      transformHover: 'none',
    },
  },
  components: {
    button: {
      padding: '0.75rem 1.75rem',
      fontFamily: "'Helvetica Neue', Helvetica, 'Inter', sans-serif",
      fontSize: '0.8125rem',
      fontWeight: 700,
      letterSpacing: '0.08em',
      textTransform: 'uppercase',
      borderRadius: '0px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#000000',
      background: '#000000',
      color: '#ffffff',
      boxShadow: 'none',
      transition: 'background-color 140ms ease, border-color 140ms ease, color 140ms ease',
      hover: {
        background: '#dc2626',
        borderColor: '#dc2626',
        color: '#ffffff',
      },
      active: {
        background: '#b91c1c',
        borderColor: '#b91c1c',
      },
      focusRing: '0 0 0 2px rgba(220, 38, 38, 0.35)',
    },
    card: {
      padding: '2rem',
      borderRadius: '0px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#000000',
      background: '#ffffff',
      color: '#000000',
      boxShadow: 'none',
      transition: 'border-color 140ms ease',
      hover: {
        borderColor: '#dc2626',
      },
    },
    heading: {
      fontFamily: "'Helvetica Neue', Helvetica, 'Inter', sans-serif",
      fontWeight: 900,
      letterSpacing: '-0.04em',
      lineHeight: 1.05,
      color: '#000000',
    },
    paragraph: {
      fontFamily: "'Helvetica Neue', Helvetica, 'Inter', sans-serif",
      fontSize: '1rem',
      lineHeight: 1.6,
      color: '#18181b',
    },
    input: {
      padding: '0.75rem 1rem',
      fontFamily: "'Helvetica Neue', Helvetica, 'Inter', sans-serif",
      fontSize: '0.9375rem',
      borderRadius: '0px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#000000',
      background: '#ffffff',
      color: '#000000',
      placeholderColor: '#71717a',
      focusBorderColor: '#dc2626',
      focusRing: '0 0 0 1px #dc2626',
      transition: 'border-color 120ms ease',
    },
    badge: {
      padding: '0.25rem 0.6rem',
      fontFamily: "'Helvetica Neue', Helvetica, 'Inter', sans-serif",
      fontSize: '0.75rem',
      fontWeight: 700,
      letterSpacing: '0.08em',
      textTransform: 'uppercase',
      borderRadius: '0px',
      borderWidth: '0px',
      borderStyle: 'solid',
      borderColor: 'transparent',
      background: '#000000',
      color: '#ffffff',
    },
    section: {
      padding: '3.5rem 2rem',
      background: '#ffffff',
      borderColor: '#000000',
      borderWidth: '1px',
      borderStyle: 'none',
    },
    page: {
      background: '#ffffff',
      color: '#000000',
      fontFamily: "'Helvetica Neue', Helvetica, 'Inter', sans-serif",
    },
  },
};

export { swissDesignSemanticCss } from './rules';
