import { StyleDefinition } from '../../core/types/style-definition';

export const luxuryTypographyStyle: StyleDefinition = {
  id: 'luxury-typography',
  name: 'Luxury Typography',
  description: 'Editorial high-fashion restraint, dramatic Didone serif display, whisper-quiet uppercase sans, champagne accents, and generous breathing room.',
  metadata: {
    version: '1.0.0',
    category: 'Modern',
    tags: ['luxury-typography', 'editorial', 'didone', 'high-fashion', 'prestige', 'restraint', 'typography-first'],
  },
  tokens: {
    colors: {
      background: '#faf8f5', // Warm luxury editorial paper
      surface: '#ffffff',
      surfaceSubtle: '#f5f2eb',
      textPrimary: '#121211', // Deep charcoal noir ink
      textSecondary: '#54504a',
      textMuted: '#8c867e',
      primary: '#121211',
      primaryHover: '#2b2826',
      primaryText: '#faf8f5',
      accent: '#c2a67e', // Subtle muted champagne
      border: '#eae6df', // Delicate warm hairline
      borderStrong: '#121211',
      ring: 'rgba(194, 166, 126, 0.35)',
    },
    typography: {
      fontFamilyBase: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      fontFamilyHeading: "'Playfair Display', 'Cormorant Garamond', 'Bodoni MT', 'Cinzel', 'Georgia', serif",
      fontFamilyMono: "'JetBrains Mono', monospace",
      fontSizeXs: '0.6875rem',
      fontSizeSm: '0.78125rem',
      fontSizeBase: '1.03125rem',
      fontSizeLg: '1.35rem',
      fontSizeXl: '2rem',
      fontSize2xl: '3.25rem',
      fontWeightNormal: 400,
      fontWeightMedium: 500,
      fontWeightBold: 600,
      lineHeightBase: 1.85,
      lineHeightHeading: 1.05,
      letterSpacingBase: '0.01em',
      letterSpacingHeading: '-0.025em',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1.5rem',
      lg: '3rem',
      xl: '4.5rem',
      '2xl': '7rem',
    },
    radii: {
      none: '0px',
      sm: '0px', // Crisp architectural geometry
      md: '1px',
      lg: '2px',
      full: '9999px',
    },
    borders: {
      widthThin: '1px',
      widthBase: '1px',
      widthThick: '1.5px',
      style: 'solid',
    },
    shadows: {
      none: 'none',
      sm: '0 2px 10px rgba(18, 18, 17, 0.02)',
      md: '0 4px 18px rgba(18, 18, 17, 0.04)',
      lg: '0 8px 30px rgba(18, 18, 17, 0.06)',
      glow: 'none',
    },
    motion: {
      durationFast: '160ms',
      durationNormal: '240ms',
      easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    },
    effects: {
      backdropBlur: 'none',
      transformHover: 'none',
    },
  },
  components: {
    button: {
      padding: '0.95rem 2.5rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.71875rem',
      fontWeight: 600,
      letterSpacing: '0.22em',
      textTransform: 'uppercase',
      borderRadius: '0px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#121211',
      background: '#121211',
      color: '#faf8f5',
      boxShadow: 'none',
      transition: 'all 180ms cubic-bezier(0.16, 1, 0.3, 1)',
      hover: {
        background: '#2b2826',
        borderColor: '#2b2826',
        color: '#ffffff',
      },
      active: {
        background: '#000000',
        borderColor: '#000000',
      },
      focusRing: '0 0 0 2px rgba(194, 166, 126, 0.4)',
    },
    card: {
      padding: '3.25rem 2.25rem',
      borderRadius: '0px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#eae6df',
      background: '#ffffff',
      color: '#121211',
      boxShadow: 'none',
      transition: 'border-color 200ms ease',
      hover: {
        borderColor: '#121211',
      },
    },
    heading: {
      fontFamily: "'Playfair Display', 'Cormorant Garamond', 'Bodoni MT', 'Cinzel', 'Georgia', serif",
      fontWeight: 400,
      letterSpacing: '-0.025em',
      lineHeight: 1.05,
      color: '#121211',
    },
    paragraph: {
      fontFamily: "'Inter', -apple-system, sans-serif",
      fontSize: '1.03125rem',
      lineHeight: 1.85,
      color: '#4a4744',
    },
    input: {
      padding: '0.95rem 1.15rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.9375rem',
      borderRadius: '0px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#eae6df',
      background: '#ffffff',
      color: '#121211',
      placeholderColor: '#8c867e',
      focusBorderColor: '#121211',
      focusRing: 'none',
      transition: 'border-color 180ms ease',
    },
    badge: {
      padding: '0.35rem 0.85rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.625rem',
      fontWeight: 600,
      letterSpacing: '0.28em',
      textTransform: 'uppercase',
      borderRadius: '0px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#eae6df',
      background: '#faf8f5',
      color: '#121211',
    },
    section: {
      padding: '5rem 2rem',
      background: 'transparent',
      borderColor: '#eae6df',
      borderWidth: '1px',
      borderStyle: 'none',
    },
    page: {
      background: '#faf8f5',
      color: '#121211',
      fontFamily: "'Inter', -apple-system, sans-serif",
    },
  },
};

export { luxuryTypographySemanticCss } from './rules';
