import { StyleDefinition } from '../../core/types/style-definition';

export const y2kAestheticStyle: StyleDefinition = {
  id: 'y2k-aesthetic',
  name: 'Y2K Aesthetic',
  description: 'Year 2000 metallic chrome, glossy aqua gel buttons, bubbly translucency, and cyber optimism.',
  metadata: {
    version: '1.0.0',
    category: 'Retro & Heritage',
    tags: ['y2k', 'y2k-aesthetic', 'futuristic', 'chrome', 'aqua-gel', 'cyber', 'retro-futurism', '2000s'],
  },
  tokens: {
    colors: {
      background: '#f1f5f9', // Pearlescent ice
      surface: '#ffffff',
      surfaceSubtle: '#f0f6fc',
      textPrimary: '#0f172a', // Cosmic deep navy
      textSecondary: '#334155',
      textMuted: '#64748b',
      primary: '#0284c7', // Electric cyber aqua/blue
      primaryHover: '#2563eb',
      primaryText: '#ffffff',
      accent: '#06b6d4', // Cyber cyan
      border: '#cbdceb',
      borderStrong: '#94b8d7',
      ring: 'rgba(2, 132, 199, 0.35)',
    },
    typography: {
      fontFamilyBase: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      fontFamilyHeading: "'Space Grotesk', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      fontFamilyMono: "'JetBrains Mono', monospace",
      fontSizeXs: '0.6875rem',
      fontSizeSm: '0.8125rem',
      fontSizeBase: '1.0125rem',
      fontSizeLg: '1.25rem',
      fontSizeXl: '2rem',
      fontSize2xl: '3rem',
      fontWeightNormal: 400,
      fontWeightMedium: 600,
      fontWeightBold: 800,
      lineHeightBase: 1.65,
      lineHeightHeading: 1.1,
      letterSpacingBase: '-0.01em',
      letterSpacingHeading: '-0.03em',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1.25rem',
      lg: '2rem',
      xl: '3.5rem',
      '2xl': '5.5rem',
    },
    radii: {
      none: '0px',
      sm: '8px',
      md: '16px',
      lg: '22px',
      full: '9999px',
    },
    borders: {
      widthThin: '1px',
      widthBase: '1px',
      widthThick: '2px',
      style: 'solid',
    },
    shadows: {
      none: 'none',
      sm: '0 2px 6px rgba(15, 23, 42, 0.05), inset 0 1px 0 #ffffff',
      md: '0 6px 18px rgba(15, 23, 42, 0.06), inset 0 1px 0 #ffffff',
      lg: '0 12px 32px rgba(2, 132, 199, 0.15), inset 0 1px 0 #ffffff',
      glow: '0 0 16px rgba(2, 132, 199, 0.4)',
    },
    motion: {
      durationFast: '120ms',
      durationNormal: '200ms',
      easing: 'ease',
    },
    effects: {
      backdropBlur: 'none',
      transformHover: 'translateY(-2px)',
    },
  },
  components: {
    button: {
      padding: '0.65rem 1.6rem',
      fontFamily: "'Space Grotesk', sans-serif",
      fontSize: '0.875rem',
      fontWeight: 700,
      letterSpacing: '0.04em',
      textTransform: 'uppercase',
      borderRadius: '9999px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#0369a1',
      background: 'linear-gradient(180deg, #38bdf8 0%, #0284c7 48%, #0369a1 52%, #0284c7 100%)',
      color: '#ffffff',
      boxShadow: 'inset 0 1px 1px rgba(255, 255, 255, 0.8), inset 0 -2px 4px rgba(0, 0, 0, 0.2), 0 4px 12px rgba(2, 132, 199, 0.35)',
      transition: 'all 150ms ease',
      hover: {
        background: 'linear-gradient(180deg, #60a5fa 0%, #2563eb 48%, #1d4ed8 52%, #2563eb 100%)',
        borderColor: '#1d4ed8',
        color: '#ffffff',
      },
      active: {
        background: '#0369a1',
        borderColor: '#0369a1',
      },
      focusRing: '0 0 0 3px rgba(2, 132, 199, 0.35)',
    },
    card: {
      padding: '2rem',
      borderRadius: '18px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#cbdceb',
      background: 'linear-gradient(180deg, rgba(255, 255, 255, 0.92) 0%, rgba(240, 246, 253, 0.85) 100%)',
      color: '#0f172a',
      boxShadow: '0 6px 18px rgba(15, 23, 42, 0.04), inset 0 1px 0 rgba(255, 255, 255, 0.9)',
      transition: 'all 180ms ease',
      hover: {
        borderColor: '#7dd3fc',
      },
    },
    heading: {
      fontFamily: "'Space Grotesk', -apple-system, sans-serif",
      fontWeight: 800,
      letterSpacing: '-0.03em',
      lineHeight: 1.1,
      color: '#0f172a',
    },
    paragraph: {
      fontFamily: "'Inter', -apple-system, sans-serif",
      fontSize: '1.0125rem',
      lineHeight: 1.65,
      color: '#334155',
    },
    input: {
      padding: '0.7rem 1.1rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.9375rem',
      borderRadius: '12px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#b8cee2',
      background: '#ffffff',
      color: '#0f172a',
      placeholderColor: '#94a3b8',
      focusBorderColor: '#0284c7',
      focusRing: '0 0 0 3px rgba(2, 132, 199, 0.25)',
      transition: 'all 150ms ease',
    },
    badge: {
      padding: '0.25rem 0.75rem',
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: '0.6875rem',
      fontWeight: 700,
      letterSpacing: '0.12em',
      textTransform: 'uppercase',
      borderRadius: '9999px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#7dd3fc',
      background: 'linear-gradient(180deg, #ffffff 0%, #e0f2fe 100%)',
      color: '#0284c7',
    },
    section: {
      padding: '4rem 2rem',
      background: 'transparent',
      borderColor: '#cbdceb',
      borderWidth: '1px',
      borderStyle: 'none',
    },
    page: {
      background: '#f1f5f9',
      color: '#0f172a',
      fontFamily: "'Space Grotesk', -apple-system, sans-serif",
    },
  },
};

export { y2kAestheticSemanticCss } from './rules';
