import { StyleDefinition } from '../../core/types/style-definition';

export const pixelArtStyle: StyleDefinition = {
  id: 'pixel-art',
  name: 'Pixel Art',
  description: '8-bit and 16-bit arcade aesthetics, aliased stepped borders, bitmap display typography, and retro gaming interfaces.',
  metadata: {
    version: '1.0.0',
    category: 'Retro & Heritage',
    tags: ['pixel-art', '8-bit', '16-bit', 'retro', 'gaming', 'arcade', 'bitmap'],
  },
  tokens: {
    colors: {
      background: '#12131c', // Deep retro console void
      surface: '#1a1d2e', // Beveled 8-bit dialog plate
      surfaceSubtle: '#242942',
      textPrimary: '#ffffff', // Crisp arcade white
      textSecondary: '#cbd5e1',
      textMuted: '#64748b',
      primary: '#22c55e', // Arcade Green
      primaryHover: '#4ade80',
      primaryText: '#000000',
      accent: '#facc15', // Coin Gold
      border: '#000000', // Heavy 8-bit outline
      borderStrong: '#22c55e',
      ring: '#22c55e',
    },
    typography: {
      fontFamilyBase: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      fontFamilyHeading: "'Press Start 2P', monospace",
      fontFamilyMono: "'Silkscreen', 'Press Start 2P', monospace",
      fontSizeXs: '0.625rem',
      fontSizeSm: '0.75rem',
      fontSizeBase: '1rem',
      fontSizeLg: '1.25rem',
      fontSizeXl: '1.5rem',
      fontSize2xl: '1.85rem',
      fontWeightNormal: 400,
      fontWeightMedium: 400,
      fontWeightBold: 700,
      lineHeightBase: 1.65,
      lineHeightHeading: 1.5,
      letterSpacingBase: '0em',
      letterSpacingHeading: '0.02em',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1.25rem',
      lg: '2rem',
      xl: '3.5rem',
      '2xl': '5rem',
    },
    radii: {
      none: '0px',
      sm: '0px',
      md: '0px',
      lg: '0px',
      full: '0px',
    },
    borders: {
      widthThin: '2px',
      widthBase: '3px',
      widthThick: '4px',
      style: 'solid',
    },
    shadows: {
      none: 'none',
      sm: '2px 2px 0px #000000',
      md: '4px 4px 0px #000000',
      lg: '6px 6px 0px #000000',
      glow: '0 0 0 2px #22c55e',
    },
    motion: {
      durationFast: '0ms',
      durationNormal: '0ms',
      easing: 'steps(2, jump-none)',
    },
    effects: {
      backdropBlur: '0px',
      transformHover: 'translate(-2px, -2px)',
    },
  },
  components: {
    button: {
      padding: '0.85rem 1.65rem',
      fontFamily: "'Press Start 2P', monospace",
      fontSize: '0.6875rem',
      fontWeight: 400,
      letterSpacing: '0.05em',
      textTransform: 'uppercase',
      borderRadius: '0px',
      borderWidth: '3px',
      borderStyle: 'solid',
      borderColor: '#000000',
      background: '#22c55e',
      color: '#000000',
      boxShadow: '4px 4px 0px #000000',
      transition: 'none',
      hover: {
        background: '#4ade80',
        borderColor: '#000000',
        color: '#000000',
      },
      active: {
        background: '#16a34a',
        borderColor: '#000000',
      },
      focusRing: '0 0 0 2px #22c55e',
    },
    card: {
      padding: '2rem',
      borderRadius: '0px',
      borderWidth: '3px',
      borderStyle: 'solid',
      borderColor: '#000000',
      background: '#1a1d2e',
      color: '#ffffff',
      boxShadow: '4px 4px 0px #000000',
      transition: 'none',
      hover: {
        borderColor: '#000000',
      },
    },
    heading: {
      fontFamily: "'Press Start 2P', monospace",
      fontWeight: 400,
      letterSpacing: '0.02em',
      lineHeight: 1.5,
      color: '#ffffff',
    },
    paragraph: {
      fontFamily: "'Inter', sans-serif",
      fontSize: '1rem',
      lineHeight: 1.65,
      color: '#cbd5e1',
    },
    input: {
      padding: '0.85rem 1.15rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.9375rem',
      borderRadius: '0px',
      borderWidth: '2px',
      borderStyle: 'solid',
      borderColor: '#374151',
      background: '#12131c',
      color: '#ffffff',
      placeholderColor: '#64748b',
      focusBorderColor: '#22c55e',
      focusRing: '0 0 0 2px #22c55e',
      transition: 'none',
    },
    badge: {
      padding: '0.4rem 0.75rem',
      fontFamily: "'Press Start 2P', monospace",
      fontSize: '0.625rem',
      fontWeight: 400,
      letterSpacing: '0.08em',
      textTransform: 'uppercase',
      borderRadius: '0px',
      borderWidth: '2px',
      borderStyle: 'solid',
      borderColor: '#000000',
      background: '#facc15',
      color: '#000000',
    },
    section: {
      padding: '4rem 2rem',
      background: 'transparent',
      borderColor: '#000000',
      borderWidth: '0px',
      borderStyle: 'none',
    },
    page: {
      background: '#12131c',
      color: '#ffffff',
      fontFamily: "'Inter', sans-serif",
    },
  },
};

export { pixelArtSemanticCss } from './rules';
