import { StyleDefinition } from '../../core/types/style-definition';

export const wabiSabiStyle: StyleDefinition = {
  id: 'wabi-sabi',
  name: 'Wabi-Sabi',
  description: 'Organic asymmetry, tranquil negative space, warm handmade washi paper tones, natural stoneware textures, serene sumi ink typography, and mindful Japanese aesthetic harmony.',
  metadata: {
    version: '1.0.0',
    category: 'Artistic & Organic',
    tags: ['wabi-sabi', 'zen', 'organic', 'asymmetry', 'natural', 'earthy', 'japanese'],
  },
  compositionConfig: {
    containerPhilosophy: 'borderless',
    groupingPhilosophy: 'hairline-list',
    featurePresentation: 'borderless-editorial',
    heroMode: 'editorial-split',
    maxWidth: '1080px',
    alignment: 'asymmetric-left',
    density: 'spacious',
    hasStructuralBorders: false,
    hasAsymmetricOffsets: true,
    hasDecorativeFraming: false,
  },
  tokens: {
    colors: {
      background: '#f7f4ee', // Warm handmade washi rice paper
      surface: '#faf7f2',
      surfaceSubtle: '#ede8df',
      textPrimary: '#292524', // Deep sumi ink
      textSecondary: '#57534e',
      textMuted: '#78716c',
      primary: '#4d7c0f', // Ceremonial matcha green
      primaryHover: '#3f6212',
      primaryText: '#ffffff',
      accent: '#c2410c', // Fired earthenware terracotta
      border: '#d6cfc4', // Natural stoneware edge
      borderStrong: '#78716c',
      ring: 'rgba(77, 124, 15, 0.3)',
    },
    typography: {
      fontFamilyBase: "'Inter', -apple-system, sans-serif",
      fontFamilyHeading: "'Cormorant Garamond', 'Georgia', 'Noto Serif', serif",
      fontFamilyMono: "'JetBrains Mono', monospace",
      fontSizeXs: '0.8125rem',
      fontSizeSm: '0.9375rem',
      fontSizeBase: '1.0625rem',
      fontSizeLg: '1.35rem',
      fontSizeXl: '1.875rem',
      fontSize2xl: '2.5rem',
      fontWeightNormal: 400,
      fontWeightMedium: 500,
      fontWeightBold: 600,
      lineHeightBase: 1.7,
      lineHeightHeading: 1.25,
      letterSpacingBase: '0.01em',
      letterSpacingHeading: '-0.02em',
    },
    spacing: {
      xs: '0.35rem',
      sm: '0.75rem',
      md: '1.5rem',
      lg: '2.5rem',
      xl: '4rem',
      '2xl': '6rem',
    },
    radii: {
      none: '0px',
      sm: '6px',
      md: '12px',
      lg: '20px',
      full: '9999px',
    },
    borders: {
      widthThin: '1px',
      widthBase: '1px',
      widthThick: '2px',
      style: 'solid',
    },
    shadows: {
      none: 'none',
      sm: '0 2px 8px rgba(41, 37, 36, 0.04)',
      md: '0 6px 24px rgba(41, 37, 36, 0.06)',
      lg: '0 12px 36px rgba(41, 37, 36, 0.08)',
      glow: '0 0 0 3px rgba(77, 124, 15, 0.2)',
    },
    motion: {
      durationFast: '200ms',
      durationNormal: '350ms',
      easing: 'cubic-bezier(0.25, 1, 0.5, 1)',
    },
    effects: {
      backdropBlur: 'none',
      transformHover: 'translateY(-2px)',
    },
  },
  components: {
    button: {
      padding: '0.75rem 1.75rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.875rem',
      fontWeight: 500,
      letterSpacing: '0.04em',
      borderRadius: '8px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#4d7c0f',
      background: '#4d7c0f',
      color: '#ffffff',
      boxShadow: '0 2px 8px rgba(77, 124, 15, 0.2)',
      transition: 'all 250ms ease',
      hover: {
        background: '#3f6212',
        transform: 'translateY(-1px)',
      },
      active: {
        background: '#365314',
      },
      focusRing: '0 0 0 3px rgba(77, 124, 15, 0.2)',
    },
    card: {
      padding: '2.25rem',
      borderRadius: '12px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#d6cfc4',
      background: '#faf7f2',
      color: '#292524',
      boxShadow: '0 4px 20px rgba(41, 37, 36, 0.04)',
      transition: 'border-color 200ms ease, box-shadow 200ms ease',
      hover: {
        borderColor: '#78716c',
      },
    },
    heading: {
      fontFamily: "'Playfair Display', 'Cinzel', Georgia, serif",
      fontWeight: 500,
      letterSpacing: '0.02em',
      lineHeight: 1.2,
      color: '#292524',
      textTransform: 'none',
    },
    paragraph: {
      fontFamily: "'Inter', sans-serif",
      fontSize: '1rem',
      lineHeight: 1.65,
      color: '#44403c',
    },
    input: {
      padding: '0.75rem 1rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.9375rem',
      borderRadius: '8px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#d6cfc4',
      background: '#ffffff',
      color: '#292524',
      placeholderColor: '#78716c',
      boxShadow: 'none',
      focusBorderColor: '#4d7c0f',
      focusRing: '0 0 0 3px rgba(77, 124, 15, 0.15)',
      transition: 'border-color 200ms ease',
    },
    badge: {
      padding: '0.3rem 0.75rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.75rem',
      fontWeight: 500,
      letterSpacing: '0.04em',
      borderRadius: '9999px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#d6cfc4',
      background: '#ede8df',
      color: '#57534e',
    },
    section: {
      padding: '4rem 2rem',
      background: '#f7f4ee',
      borderColor: '#d6cfc4',
      borderWidth: '1px',
      borderStyle: 'solid',
    },
    page: {
      background: '#f7f4ee',
      color: '#292524',
      fontFamily: "'Inter', sans-serif",
    },
  },
};

export { wabiSabiSemanticCss } from './rules';
