import { StyleDefinition } from '../../core/types/style-definition';

export const solarpunkStyle: StyleDefinition = {
  id: 'solarpunk',
  name: 'Solarpunk',
  description: 'Lush botanical curves, stained-glass light refractions, warm polished brass, verdant leaves, and an optimistic ecological future.',
  metadata: {
    version: '1.0.0',
    category: 'Artistic & Organic',
    tags: ['solarpunk', 'nature', 'botanical', 'solar', 'futurism', 'eco', 'brass'],
  },
  compositionConfig: {
    containerPhilosophy: 'card-based',
    groupingPhilosophy: 'grid',
    featurePresentation: 'card-grid',
    heroMode: 'centered-bold',
    maxWidth: '1200px',
    alignment: 'center',
    density: 'balanced',
    hasStructuralBorders: true,
    hasAsymmetricOffsets: false,
    hasDecorativeFraming: true,
  },
  tokens: {
    colors: {
      background: '#f0fdf4',
      surface: '#ffffff',
      surfaceSubtle: '#f7fdf7',
      textPrimary: '#14532d',
      textSecondary: '#166534',
      textMuted: '#4ade80',
      primary: '#15803d',
      primaryHover: '#166534',
      primaryText: '#ffffff',
      accent: '#eab308',
      border: 'rgba(34, 197, 94, 0.25)',
      borderStrong: '#15803d',
      ring: 'rgba(34, 197, 94, 0.35)',
    },
    typography: {
      fontFamilyBase: "'Plus Jakarta Sans', 'Inter', -apple-system, sans-serif",
      fontFamilyHeading: "'Outfit', 'Plus Jakarta Sans', sans-serif",
      fontFamilyMono: "'JetBrains Mono', monospace",
      fontSizeXs: '0.8125rem',
      fontSizeSm: '0.9375rem',
      fontSizeBase: '1.0625rem',
      fontSizeLg: '1.35rem',
      fontSizeXl: '1.875rem',
      fontSize2xl: '2.5rem',
      fontWeightNormal: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
      lineHeightBase: 1.7,
      lineHeightHeading: 1.2,
      letterSpacingBase: '0.01em',
      letterSpacingHeading: '-0.02em',
    },
    spacing: {
      xs: '0.35rem',
      sm: '0.75rem',
      md: '1.5rem',
      lg: '2.5rem',
      xl: '4rem',
      '2xl': '6rem',
    },
    radii: {
      none: '0px',
      sm: '6px',
      md: '14px',
      lg: '22px',
      full: '9999px',
    },
    borders: {
      widthThin: '1px',
      widthBase: '1px',
      widthThick: '2px',
      style: 'solid',
    },
    shadows: {
      none: 'none',
      sm: '0 2px 10px rgba(22, 101, 52, 0.05)',
      md: '0 8px 24px rgba(22, 101, 52, 0.08)',
      lg: '0 16px 40px rgba(22, 101, 52, 0.12)',
      glow: '0 0 16px rgba(234, 179, 8, 0.25)',
    },
    motion: {
      durationFast: '200ms',
      durationNormal: '300ms',
      easing: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
    },
    effects: {
      backdropBlur: 'blur(12px)',
      transformHover: 'translateY(-3px)',
    },
  },
  components: {
    button: {
      padding: '0.85rem 2rem',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '0.9375rem',
      fontWeight: 700,
      letterSpacing: '0.02em',
      borderRadius: '18px 4px 18px 4px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: 'rgba(234, 179, 8, 0.4)',
      background: 'linear-gradient(135deg, #15803d 0%, #166534 100%)',
      color: '#ffffff',
      boxShadow: '0 4px 16px rgba(22, 101, 52, 0.25)',
      transition: 'all 250ms ease',
      hover: {
        background: 'linear-gradient(135deg, #16a34a 0%, #15803d 100%)',
        transform: 'translateY(-2px)',
      },
      active: {
        background: '#14532d',
      },
      focusRing: '0 0 0 3px rgba(34, 197, 94, 0.35)',
    },
    card: {
      padding: '2.25rem',
      borderRadius: '20px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: 'rgba(34, 197, 94, 0.25)',
      background: 'rgba(255, 255, 255, 0.9)',
      color: '#14532d',
      boxShadow: '0 8px 30px rgba(22, 101, 52, 0.06)',
      transition: 'all 250ms ease',
      hover: {
        borderColor: '#22c55e',
      },
    },
    heading: {
      fontFamily: "'Outfit', 'Plus Jakarta Sans', sans-serif",
      fontWeight: 800,
      letterSpacing: '-0.02em',
      lineHeight: 1.2,
      color: '#14532d',
      textTransform: 'none',
    },
    paragraph: {
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '1rem',
      lineHeight: 1.7,
      color: '#166534',
    },
    input: {
      padding: '0.85rem 1.25rem',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '0.95rem',
      borderRadius: '12px',
      borderWidth: '1.5px',
      borderStyle: 'solid',
      borderColor: 'rgba(34, 197, 94, 0.3)',
      background: '#ffffff',
      color: '#14532d',
      placeholderColor: '#4ade80',
      boxShadow: 'none',
      focusBorderColor: '#22c55e',
      focusRing: '0 0 0 3px rgba(34, 197, 94, 0.2)',
      transition: 'all 200ms ease',
    },
    badge: {
      padding: '0.35rem 0.85rem',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      fontSize: '0.75rem',
      fontWeight: 700,
      letterSpacing: '0.04em',
      borderRadius: '9999px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: 'rgba(34, 197, 94, 0.3)',
      background: 'rgba(34, 197, 94, 0.15)',
      color: '#15803d',
    },
    section: {
      padding: '4rem 2rem',
      background: '#f0fdf4',
      borderColor: 'rgba(34, 197, 94, 0.25)',
      borderWidth: '1px',
      borderStyle: 'solid',
    },
    page: {
      background: '#f0fdf4',
      color: '#14532d',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
    },
  },
};

export { solarpunkSemanticCss } from './rules';
