import { StyleDefinition } from '../../core/types/style-definition';

export const minimalismStyle: StyleDefinition = {
  id: 'minimalism',
  name: 'Minimalism',
  description: 'Clean, spacious, highly restrained aesthetic with subtle hairline borders, muted tones, and expansive negative space.',
  metadata: {
    version: '1.0.0',
    category: 'Modern',
    tags: ['minimalism', 'clean', 'simple', 'hairline', 'monochrome', 'negative-space'],
  },
  tokens: {
    colors: {
      background: '#ffffff',
      surface: '#ffffff',
      surfaceSubtle: '#f5f5f4',
      textPrimary: '#18181b', // Crisp zinc-900 typography
      textSecondary: '#52525b', // Refined slate gray
      textMuted: '#71717a',
      primary: '#18181b',
      primaryHover: '#27272a',
      primaryText: '#ffffff',
      accent: '#18181b',
      border: '#e5e5e5', // Delicate hairline rule
      borderStrong: '#d4d4d4',
      ring: 'rgba(0, 0, 0, 0.1)',
    },
    typography: {
      fontFamilyBase: "'Inter', -apple-system, sans-serif",
      fontFamilyHeading: "'Inter', -apple-system, sans-serif",
      fontFamilyMono: "'JetBrains Mono', monospace",
      fontSizeXs: '0.75rem',
      fontSizeSm: '0.8125rem',
      fontSizeBase: '0.9375rem',
      fontSizeLg: '1.1875rem',
      fontSizeXl: '1.5rem',
      fontSize2xl: '2.25rem',
      fontWeightNormal: 400,
      fontWeightMedium: 500,
      fontWeightBold: 600,
      lineHeightBase: 1.65,
      lineHeightHeading: 1.15,
      letterSpacingBase: '0em',
      letterSpacingHeading: '-0.03em',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1.25rem',
      lg: '2rem',
      xl: '3.5rem', // Generous structural whitespace
      '2xl': '5.5rem',
    },
    radii: {
      none: '0px',
      sm: '3px',
      md: '5px',
      lg: '8px',
      full: '9999px',
    },
    borders: {
      widthThin: '1px',
      widthBase: '1px',
      widthThick: '1.5px',
      style: 'solid',
    },
    shadows: {
      none: 'none',
      sm: '0 1px 2px 0 rgba(0, 0, 0, 0.02)',
      md: '0 2px 4px 0 rgba(0, 0, 0, 0.03)',
      lg: '0 4px 8px 0 rgba(0, 0, 0, 0.04)',
      glow: 'none',
    },
    motion: {
      durationFast: '150ms',
      durationNormal: '250ms',
      easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    },
    effects: {
      backdropBlur: 'none',
      transformHover: 'none',
    },
  },
  components: {
    button: {
      padding: '0.625rem 1.25rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.8125rem',
      fontWeight: 500,
      letterSpacing: '0.02em',
      borderRadius: '2px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#18181b',
      background: '#18181b',
      color: '#ffffff',
      boxShadow: 'none',
      transition: 'all 150ms ease',
      hover: {
        background: '#27272a',
        transform: 'none',
        boxShadow: 'none',
      },
      active: {
        transform: 'scale(0.99)',
        boxShadow: 'none',
      },
      focusRing: '0 0 0 2px rgba(17, 17, 17, 0.15)',
    },
    card: {
      padding: '1.75rem 0',
      borderRadius: '0px',
      borderWidth: '0px',
      borderStyle: 'none',
      borderColor: 'transparent',
      background: 'transparent',
      color: '#111111',
      boxShadow: 'none',
      transition: 'opacity 150ms ease',
      hover: {
        transform: 'none',
        boxShadow: 'none',
      },
    },
    heading: {
      fontFamily: "'Inter', sans-serif",
      fontWeight: 500,
      letterSpacing: '-0.03em',
      lineHeight: 1.15,
      color: '#111111',
    },
    paragraph: {
      fontFamily: "'Inter', sans-serif",
      fontSize: '1rem',
      lineHeight: 1.65,
      color: '#52525b',
    },
    input: {
      padding: '0.625rem 0.875rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.875rem',
      borderRadius: '2px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#e5e5e5',
      background: '#ffffff',
      color: '#111111',
      placeholderColor: '#a1a1aa',
      focusBorderColor: '#111111',
      focusRing: '0 0 0 1px #111111',
      transition: 'border-color 150ms ease',
    },
    badge: {
      padding: '0.2rem 0.5rem',
      fontFamily: "'Inter', sans-serif",
      fontSize: '0.6875rem',
      fontWeight: 500,
      letterSpacing: '0.04em',
      textTransform: 'uppercase',
      borderRadius: '2px',
      borderWidth: '0px',
      borderStyle: 'none',
      borderColor: 'transparent',
      background: '#f5f5f4',
      color: '#71717a',
    },
    section: {
      padding: '4.5rem 2rem',
      background: '#fafaf9',
      borderColor: '#e5e5e5',
      borderWidth: '1px',
      borderStyle: 'none',
    },
    page: {
      background: '#ffffff',
      color: '#18181b',
      fontFamily: "'Inter', sans-serif",
    },
  },
};

export { minimalistSemanticCss } from './rules';

