import { StyleDefinition } from '../../core/types/style-definition';

export const baseStyle: StyleDefinition = {
  id: 'base',
  name: 'Base Neutral Style',
  description: 'Neutral, accessible, balanced default design language with subtle curves and calm typography.',
  metadata: {
    version: '1.0.0',
    isBase: true,
    tags: ['neutral', 'base', 'default', 'accessible'],
  },
  tokens: {
    colors: {
      background: '#f8fafc',
      surface: '#ffffff',
      surfaceSubtle: '#f1f5f9',
      textPrimary: '#0f172a',
      textSecondary: '#475569',
      textMuted: '#94a3b8',
      primary: '#2563eb',
      primaryHover: '#1d4ed8',
      primaryText: '#ffffff',
      accent: '#38bdf8',
      border: '#e2e8f0',
      borderStrong: '#cbd5e1',
      ring: 'rgba(37, 99, 235, 0.25)',
    },
    typography: {
      fontFamilyBase: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      fontFamilyHeading: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      fontFamilyMono: "'JetBrains Mono', monospace",
      fontSizeXs: '0.75rem',
      fontSizeSm: '0.875rem',
      fontSizeBase: '1rem',
      fontSizeLg: '1.125rem',
      fontSizeXl: '1.5rem',
      fontSize2xl: '2rem',
      fontWeightNormal: 400,
      fontWeightMedium: 500,
      fontWeightBold: 600,
      lineHeightBase: 1.5,
      lineHeightHeading: 1.25,
      letterSpacingBase: '0em',
      letterSpacingHeading: '-0.02em',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1rem',
      lg: '1.5rem',
      xl: '2rem',
      '2xl': '3rem',
    },
    radii: {
      none: '0px',
      sm: '6px',
      md: '10px',
      lg: '16px',
      full: '9999px',
    },
    borders: {
      widthThin: '1px',
      widthBase: '1px',
      widthThick: '2px',
      style: 'solid',
    },
    shadows: {
      none: 'none',
      sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
      md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)',
      lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.1)',
      glow: '0 0 15px rgba(37, 99, 235, 0.3)',
    },
    motion: {
      durationFast: '150ms',
      durationNormal: '250ms',
      easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    },
    effects: {
      backdropBlur: 'none',
      transformHover: 'none',
    },
  },
  components: {
    button: {
      padding: '0.625rem 1.25rem',
      fontFamily: "'Inter', -apple-system, sans-serif",
      fontSize: '0.875rem',
      fontWeight: 500,
      borderRadius: '8px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: 'transparent',
      background: '#2563eb',
      color: '#ffffff',
      boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
      transition: 'all 150ms ease',
      hover: {
        background: '#1d4ed8',
        transform: 'none',
        boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
      },
      active: {
        transform: 'scale(0.98)',
        boxShadow: 'none',
      },
      focusRing: '0 0 0 3px rgba(37, 99, 235, 0.3)',
    },
    card: {
      padding: '1.5rem',
      borderRadius: '12px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#e2e8f0',
      background: '#ffffff',
      color: '#0f172a',
      boxShadow: '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1)',
      transition: 'box-shadow 200ms ease, border-color 200ms ease',
      hover: {
        transform: 'none',
        boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)',
      },
    },
    heading: {
      fontFamily: "'Inter', -apple-system, sans-serif",
      fontWeight: 600,
      letterSpacing: '-0.02em',
      lineHeight: 1.25,
      color: '#0f172a',
    },
    paragraph: {
      fontFamily: "'Inter', -apple-system, sans-serif",
      fontSize: '1rem',
      lineHeight: 1.5,
      color: '#475569',
    },
    input: {
      padding: '0.625rem 0.875rem',
      fontFamily: "'Inter', -apple-system, sans-serif",
      fontSize: '0.875rem',
      borderRadius: '8px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#cbd5e1',
      background: '#ffffff',
      color: '#0f172a',
      placeholderColor: '#94a3b8',
      focusBorderColor: '#2563eb',
      focusRing: '0 0 0 3px rgba(37, 99, 235, 0.2)',
      transition: 'border-color 150ms ease, box-shadow 150ms ease',
    },
    badge: {
      padding: '0.25rem 0.625rem',
      fontFamily: "'Inter', -apple-system, sans-serif",
      fontSize: '0.75rem',
      fontWeight: 500,
      borderRadius: '9999px',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: '#e2e8f0',
      background: '#f1f5f9',
      color: '#475569',
    },
    section: {
      padding: '3rem 1.5rem',
      background: 'transparent',
      borderColor: '#e2e8f0',
      borderWidth: '1px',
      borderStyle: 'none',
    },
    page: {
      background: '#f8fafc',
      color: '#0f172a',
      fontFamily: "'Inter', -apple-system, sans-serif",
    },
  },
};
